### ISSUE TITLE
[bug] BG2: Failing to disarm a container trap does not trigger it

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#341] opened 2019-10-11 15:43 UTC
Split from #171 

**Description**
Just checked the original game, and container traps still trigger on a failed disarm. Meanwhile in GemRB they not only fail to trigger, they may actually be disabled instead if they're one-time only (I think).

Most of container code is in Container.cpp, but it would be faster to look (break) at why Highlightable::TryDisarm does not do the job for it.

**Comment by ifyGecko** [comment] 2019-11-02 15:27
Can not reproduce in iwd1.

**Comment by caillean7** [comment] 2019-11-02 16:52
I just tested a bit in BG2 (the 'Ellesime room' in the 1st level of the starter dungeon has some good traps), and I can't reproduce either. Traps here work as intended if you fail to disarm.

**Comment by lynxlynxlynx** [comment] 2019-11-02 17:16
In iwd2 they don't trigger either and with our powers combined, I'm closing the report. :hear_no_evil:

**Comment by Tomsod** [comment] 2019-11-02 20:40
Hold your horses.  @caillean7, you were testing in AR0602, right?  Most traps there have two triggers:
```
IF
	OR(2)
		Entered([ANYONE])
		Opened([ANYONE])
THEN
...
```
But the trap I was using had only `Opened([ANYONE])`.  I just checked, if I change the script to two triggers as above, the trap triggers properly.  So that's probably the problem.  If you want to test in AR0602, it seems a drawer at (x=3060, y=2220) with Bracers of Defense and a part of the Equalizer only has `Opened()`; try disarming it.

**Comment by lynxlynxlynx** [comment] 2019-11-02 21:02
Do I understand correctly that you're saying that if the trap is using two or-ed triggers, it doesn't trigger on misdisarm, but it does if it has just Opened?

**Comment by Tomsod** [comment] 2019-11-02 21:13
No, the other way around: if the trap has two triggers, it always triggers.  If it has just `Opened()`, in GemRB it seems to only trigger on open, but not on a failed disarm.  @caillean7 apparently has tested on a trap with two triggers, so she could not reproduce the bug.

**Comment by lynxlynxlynx** [comment] 2019-11-02 21:24
We send the entered trigger message, yes.

The only trap in the first iwd2 area, in Jorun's home, has the script 00p2229.baf and both triggers, yet failing the disarm didn't launch it. So it appears like another engine difference.
```
IF
  Or(2)
    Opened([PC])
    Entered([PC])
THEN
  RESPONSE #100
    DisplayMessage(14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastTrigger,WIZARD_STINKING_CLOUD_HALF_DURATION)
END
```

**Comment by caillean7** [comment] 2019-11-03 11:13
> If you want to test in AR0602, it seems a drawer at (x=3060, y=2220) with Bracers of Defense and a part of the Equalizer only has Opened(); try disarming it.

Ah, you're right! This trap doesn't trigger on a failed disarm.

**Comment by lynxlynxlynx** [comment] 2019-12-18 17:47
So, we know that Opened should also be triggered in bg2 on a failed disarm, but not in iwd2. What is the behaviour of failed disarms in bg1, iwd and pst?

**Comment by lynxlynxlynx** [comment] 2024-11-24 09:08
Retesting iwd2 with a non-trivial container trap shows it behaves the same as bg2, so no special casing is needed.

**Closed** 2024-11-24 11:05 UTC
Labels: bug, system: core, research needed
