### ISSUE TITLE
Repeatedly casting Power of One allows to raise Strength up to 25 permanently, contrary to spell description.

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#656] opened 2020-04-08 19:03 UTC
## Description of the bug:

_«Power of One»_ should raise strength of the target character by some value, but at most to 21, and, I assume, temporarily. Instead, the effect never wears off and can be applied repeatedly.

## Expected behavior:

The effect of the spell wears off after time or rest, and the effect does not stack with itself.

## Steps to reproduce the behavior:

1. Get Dak'kon in the party.
3. Ask him to cast _«Power of One»_ on the same character several times, with rest as needed.
4. Observe the target character glow pulsating white and Strength rising up to 25, which seems to be the absolute maximum allowed by the game mechanics.
5. See the effect last arbitrarily long.

## GemRB version:

Current master, commit `4b2632ab6`.

**Comment by lynxlynxlynx** [comment] 2020-04-08 19:10
Thanks, but this is a dupe of #641, so closing. Reporting spell bugs in pst is pointless right now: see this list for an overview: https://github.com/gemrb/gemrb/issues/587#issuecomment-598983438

**Closed by lynxlynxlynx** 2020-04-08 19:10 UTC
Labels: bug, game: pst
