### ISSUE TITLE
Cannot exit dialogue sometimes

### ISSUE THREAD

**Issue by DudeMcDude** [gemrb/gemrb#1651] opened 2022-07-24 20:16 UTC
#### Bug description
Clicking on some dialogue exit choices does nothing sometimes (random?). This can mean you get stuck in dialogue.

#### Steps to reproduce
Built RelWithDebugInfo, Win64 on MSVC 2022. Could not reproduce with appveyor build.

Demo module, conversation with The Mono Man.
Dialogue choices:

>  What is your purpose here?  
>  What do you mean?  
>  Fine. Whatever, see you later.  

Occurs about 1 in 3 attempts.

When it happens, DialogHandler::DialogChoose is not getting called, either with clicking the line or pressing the number. The text line is also stuck in "Green" state (selected span gets stuck?).

I've also encountered this while running IWD2, but preferred showcasing via the demo to be "safer".

#### Screenshots

![image](https://user-images.githubusercontent.com/11220053/180664254-7476b469-51af-4272-8e75-2aef76e744e4.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

(not 100% sure it's without USE_OPENGL_BACKEND; I'm using the default specification, OPENGL_BACKEND: None)

**Comment by lynxlynxlynx** [comment] 2022-07-24 20:35
Yeah, this is a duplicate of what became of #1641.

**Closed by lynxlynxlynx** 2022-07-24 20:35 UTC
Labels: bug
