### ISSUE TITLE
[bug] iwd1 end fight: jerrod can get interrupted and not reseal the stone

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#349] opened 2019-10-20 17:55 UTC
**Describe the bug**
Jerrod comes to the rescue and for all intents and purposes closes the portal. However we do not update its graphics back to closed.

Didn't happen in the original: https://youtu.be/ZKFKEYsaJKk?t=165
Maybe he gets interrupted by attacks of #350? EDIT: yes, if a lower difficulty is picked and they're not there, he succeeds and it's not up to chance. So the bug is about interruptability ... some of the cutscenes involved change the item they have equipped, perhaps for the very same purpose. Or maybe ForceSpell should grant temporary immunity. Investigate ...

**To Reproduce**
mta('ar1104') and walk through the mirror portal. The final cutscene starts.

**Comment by lynxlynxlynx** [comment] 2019-12-18 15:47
@caillean7 A harder nut to crack, since there are scripts and items involved. What's the item switching for? If that's crippled to one item or the other, does it affect the outcome?

**Comment by caillean7** [comment] 2019-12-19 16:19
A short summary:
There are two issues here: First, the MoveToPoint action in two cutscenes doesn't work for the cornugons, meaning they're standing all the time at where Everard is casting his closing portal spell. Which leads directly to second: the presence of hostile actors / the cornugons messes with the closing portal spell.

The longwinded / detailed version:
The problem with the cornugons starts earlier than any failed casting attempts. They are present from the start and only destroy themselves if the difficulty is lower than hard. Their items are not switched, they already have everything equipped in their cre file, the scripts probably intend to make extra sure they are equipped when needed for some reason. All the cornugons' items and scripts don't seem to be the problem, because even if you remove everything, the problems still persist.

The first problem is that the cornugons are supposed to take positions to Poquelins' left and right side after they 'appear', see [this video](https://www.youtube.com/watch?v=vqevqkftKpM). This doesn't work. That's from the script EECRNENT:

```
IF
	True()
THEN
	RESPONSE #100
		CutSceneId("CORNUGON_1")
		EquipItem("APORT",0)  // No such index
		FaceObject([PC])
		Wait(1)
		HideCreature(Myself,FALSE)
		MoveToPoint([783.503])
		FaceObject([PC])
END
```

The MoveToPoint is not executed for some reason. I added debug messages (FloatMessage) before and after this line, they display fine, so the problem is with the MoveToPoint, it doesn't seem to abort executing this script. (Tried if using ActionOverride makes a difference, it doesn't) Also, adding waits or commenting out lines from the script that calls this one makes no difference. The log shows no errors.

The actual issue, that the portal doesn't get closed, is in EEENDCT4:

```
IF
	True()
THEN
	RESPONSE #100
		CutSceneId("POQUELIN")  // Revered Brother Poquelin
		StartCutSceneMode()
		HideGUI()
		MultiPlayerSync()
		SetGlobal("END_PORTAL","GLOBAL",2)
		Deactivate("GATEWAY")
		ActionOverride("EVERARD",ForceSpellPoint([603.414],INNATE_EVERARDS_PORTAL_CLOSING))  // SPIN974.SPL (No such index)
		Wait(2)
		Wait(2)
		StartCutScene("EECRNMVE")
		Wait(3)
		FaceObject([PC])
		SetDialogueRange(300)
		MultiPlayerSync()
		Wait(1)
		Dialogue(Protagonist)
END

```
EECRNMVE should cause the cornugons move towards the party:
```
IF
	True()
THEN
	RESPONSE #100
		CutSceneId("CORNUGON_1")
		MoveToPoint([783.503])
		FaceObject([PC])
END
```

Again, MoveToPoint doesn't work for them. They are still standing directly where Everard is supposed to cast his spell, and he does, but it gets messed up by the cornugons' presence. It's not  that any combat scripts of Everard's interfere with his casting the portal closing spells, I removed everything from him to no avail. What does the trick is changing the allegiance of the cornugons to 'neutral' - only then does his casting succeed completely and the portal gets closed. So somehow the presence of hostile actors hinders his spellcasting. The effects get applied to himself, he does vanish, but the portal animation doesn't get changed. That's about as far as I can get,  for now.

**Comment by caillean7** [comment] 2019-12-19 17:12
I tried how it works on the original if you have the cornugons stand in the way, and here the portal gets still closed, so the enemies don't 'catch' this projectile. So something about the targeting here is really off.

**Comment by lynxlynxlynx** [comment] 2019-12-19 17:14
Nice analysis, thanks. Looks like it's time to break on MoveToPoint and see why it is ineffectual. It appears like they abandon their path.

**Comment by caillean7** [comment] 2019-12-20 14:42
Something I didn't mention about this whole cutscene, more cosmetic:

![ev_cl_portal_spell](https://user-images.githubusercontent.com/54738589/71262004-00b51280-233f-11ea-975b-fe3efb32e3f1.jpg)

When Everard casts his spell, he turns away about 90°. A bit before that, Poquelin casts the open portal spell exactly at the same point, but he faces the portal - not sure why E. doesn't.

**Comment by lynxlynxlynx** [comment] 2019-12-21 11:35
Map::FindPath doesn't find a path in the stack (returning already at the `pos != pos2` check), so MoveToPoint aborts in the same tick it started. The path isn't found because the cornugons are too big. If you set their circle/searchmap size to 2 instead of 3, they move properly and things are fine. It looks like they can't go past Poquelin.
![image](https://user-images.githubusercontent.com/121515/71307405-38c75e80-23ee-11ea-822e-6af24e369e17.png)
![image](https://user-images.githubusercontent.com/121515/71307420-60b6c200-23ee-11ea-92a0-cf503ec216c0.png)
Did they have smaller circles in the original? Hmm ...

**Comment by caillean7** [comment] 2019-12-21 11:40
Yes, they do!

**Comment by lynxlynxlynx** [comment] 2019-12-21 11:42
How much? These are at 3, mr bad at 2, so not much space for choice.

**Comment by caillean7** [comment] 2019-12-21 11:50
Looks like it should be something like 2.5 then. The original is bigger than size 2:
![corn_IE](https://user-images.githubusercontent.com/54738589/71307547-72996480-23f0-11ea-95bb-f19e45215249.jpg)
That's with size 2 on GemRB:
![corn_GemRB](https://user-images.githubusercontent.com/54738589/71307550-7f1dbd00-23f0-11ea-92e3-f7621d23d4e3.jpg)

**Comment by caillean7** [comment] 2019-12-21 13:45
Dunno if you need to add this circle size or how to fix this properly, but for now do you want the circle size for this animation set to 2? Would make the portal closing work for the time being at least.

**Comment by lynxlynxlynx** [comment] 2019-12-21 15:39
Yep, already have it committed.

**Closed** 2019-12-21 16:09 UTC
Labels: bug, game: iwd1, research needed
