### ISSUE TITLE
[subviews] GUISTORE: invalid rooms can be chosen

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#924] opened 2020-08-30 17:31 UTC
I was investigating an older bug and hit this in the bg2 ar2202 store (NE platform guy). It's supposed to have only royal rooms and indeed, if you click any of the others, the price is -1.

Now we do take that into account in InitStoreRentWindow and the button disabling is getting called, but the net result is that they're still enabled. Works for the room pic buttons just fine. I don't see any other code touching those controls, so no idea what's going wrong. It's as if something in core was reenabling them, but I don't see that either. Any ideas?

One thing that would help track it down would be changing the signature of SetState to return something useful.

**Comment by bradallred** [comment] 2020-08-30 17:49
the problem is that `SetVarAssoc` changes the button state

**Comment by lynxlynxlynx** [comment] 2020-08-30 17:52
But SetState is called after that, not before.

**Comment by bradallred** [comment] 2020-08-30 19:22
right, but when the script hits the "royal" room (the last one) we again call `Button.SetVarAccoc("RentIndex", ...) which results in the window updating all controls with that variable assigned including the ones that were previously disabled.

**Comment by bradallred** [comment] 2020-08-30 19:25
fixed by 48b670d

**Closed by bradallred** 2020-08-30 19:25 UTC
Labels: subviews

**Comment by bradallred** [comment] 2020-08-30 19:30
This is a side effect of the buttons being part of a radio group.
