### ISSUE TITLE
Perfectionist's hell 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1991] opened 2024-02-11 17:03 UTC
#### Bug description
Misaligned buttons in main menu.

#### Steps to reproduce
1. Start BG2.
2. Click on Quit/Options. Watch the button borders.

#### Expected behavior
Aligned! Buttons! Aligned!

#### Screenshots
Open the attached files in full screen mode, and flip between them fast.
[menu.zip](https://github.com/gemrb/gemrb/files/14233237/menu.zip)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by burner1024** [comment] 2024-02-12 11:13
I looked in GUIscripts, but didn't find any coordinates.

**Comment by bradallred** [comment] 2024-02-12 18:07
we have some functions to do this sort of alignment in the CharGen. You can do something similar here.

https://github.com/gemrb/gemrb/blob/672e8315c9f8a3aaea71db0839f5e4bea849634d/gemrb/GUIScripts/bg2/CharGenCommon.py#L33-L38

**Comment by burner1024** [comment] 2024-02-15 08:50
That seems to be for the position of the window itself, not buttons within the window?

**Comment by bradallred** [comment] 2024-02-16 05:20
The problem is that the window is not aligned with the one below it. Buttons are almost always baked into the CHU background.

**Comment by burner1024** [comment] 2024-02-16 14:59
I think something else is going on here.
Here's comparison of the main screen, original and GemRB. Different screenshot resolution, but same game resolution, fullscreen view should align them perfectly.
As far as I understand, there are no overlaid windows here, just the one main window.
3 buttons are off.

[cmp.zip](https://github.com/gemrb/gemrb/files/14312518/cmp.zip)

**Comment by bradallred** [comment] 2024-02-16 17:38
right, the problem I thought you were describing we fixed in #433 using the technique I described.

But you can see for yourself in NI that the "buttons" are baked into the CHU background. The background is `GUIVERB.MOS`

<img width="559" alt="image" src="https://github.com/gemrb/gemrb/assets/1126744/9b51eada-46c1-4aa9-b898-5351e06c37b4">

> As far as I understand, there are no overlaid windows here, just the one main window.

No, that is not correct. You can see for yourself in NI or look in the Start2.py script.

**Comment by burner1024** [comment] 2024-02-16 18:24
Yes, I saw the CHUs and #433, and Start2.py.

`GUIVERB.MOS` is the 2-button overlay:
![Captura desde 2024-02-17 01-02-34](https://github.com/gemrb/gemrb/assets/1279852/d61bae95-7eed-497f-80db-d4b3fe80ced6)
It gets loaded in Exit procedure ("Are you sure you want to exit?"):
https://github.com/gemrb/gemrb/blob/90eff5fd731fed77b53f678c13add3ba8ff106e6/gemrb/GUIScripts/bg2/Start2.py#L182-L184

The screenshots I shared in the previous message are the main 6-button screen, `START.MOS`:
![Captura desde 2024-02-17 01-03-11](https://github.com/gemrb/gemrb/assets/1279852/1d4b4110-1964-418e-9468-241dd5d4e167)

https://github.com/gemrb/gemrb/blob/90eff5fd731fed77b53f678c13add3ba8ff106e6/gemrb/GUIScripts/bg2/Start2.py#L23-L24

If it were positioning, the issues would've been present on the whole top, side, bottom like [here](https://github.com/gemrb/gemrb/issues/433#issuecomment-559591248).
But in this case the misalignment is present in diagonally opposite buttons:
![1](https://github.com/gemrb/gemrb/assets/1279852/5623bda5-6fc8-4669-a186-8046b20a34a4)

I don't see how this can be happening due to bad window positioning with these MOS files in any combination. Unless I grossly misunderstand how it all works.

**Comment by lynxlynxlynx** [comment] 2024-02-16 18:58
Do I understand correctly that there should be like a 1px gap? We don't modify the MOS, so the only way that could happen is with something being overlaid on top.

**Comment by lynxlynxlynx** [comment] 2024-02-16 19:02
And that something can clearly be the buttons themselves, without an extra window, since they have their own background.

**Comment by burner1024** [comment] 2024-02-16 19:27
The 3 affected buttons should be 1-2px to the left.
If you open [these](https://github.com/gemrb/gemrb/files/14312518/cmp.zip) in fullscreen and flip between them, you can easily see the buttons shifting.

**Comment by lynxlynxlynx** [comment] 2024-02-16 21:01
Sure, but that doesn't change my point, it's the buttons (as in CHU elements) that are mispositioned. Since the GUI was hardcoded in the original, there may have been some manual moving done, but like Brad pointed out, we can as easily move the buttons ourselves.

There's nothing in the CHU that would provide any extra positional offsets.

**Comment by burner1024** [comment] 2024-02-17 07:30
Yeah, turns out buttons are also windows, and can be moved individually.

Is there supposed to be no intellisense on this or something's wrong with my environment?

![Captura desde 2024-02-17 14-28-38](https://github.com/gemrb/gemrb/assets/1279852/10044785-3197-431d-be4c-3a5421db0ee2)

**Closed** 2024-02-20 15:33 UTC
Labels: bug, system: GUI, good first issue, research needed
