### ISSUE TITLE
LINUX, Incomplete GUI view and green mask around characters. 

### ISSUE THREAD

**Issue by STyx2909** [gemrb/gemrb#1361] opened 2021-07-18 10:00 UTC
#### Bug description
Xubuntu 20.04.x. NVIDIA GEFORCE GT 220 M Cuda.

Fresh game start (Demo), latest v 0.9.0 build AppImage. Happens anytime.

Switched Nvidia drivers to Nouveau drivers, same result.
![Screenshot_2021-07-18_11-46-55](https://user-images.githubusercontent.com/76572473/126063064-aee0653a-99ea-4b04-951e-d034ccacbee6.png)

![Screenshot_2021-07-18_11-47-22](https://user-images.githubusercontent.com/76572473/126063065-bda4dddd-5a6d-411f-b0a1-1c3673ff64e9.png)

[gemrb-linux-v0.9.0.AppImage.log](https://github.com/gemrb/gemrb/files/6835987/gemrb-linux-v0.9.0.AppImage.log)

**Comment by lynxlynxlynx** [comment] 2021-07-18 10:06
Thanks, but this is a duplicate of #1286. Use the development appimage where this won't be an issue (and also the demo default resolution will be properly detected without a config).

**Closed by lynxlynxlynx** 2021-07-18 10:06 UTC
Labels: bug
