### ISSUE TITLE
Sound frequency settings get reset 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1988] opened 2024-02-09 13:40 UTC
#### Bug description
"Selection Sounds Frequency" and "Command Sounds Frequency" get reset to "Never", if you just visit the corresponding settings page and hit "Cancel", then check the settings again.
Like #1762, but for these.
![Captura desde 2024-02-09 20-36-27](https://github.com/gemrb/gemrb/assets/1279852/a5c231ca-3f4d-43c5-851d-ff66ffe528a1)

I thought it would be a similar easy fix, but there's some radio button mumbo jumbo that I can't comprehend.

#### Steps to reproduce
1. Go to character sound settings page.
2. Set frequencies to "always".
3. Click OK, return to main menu.
4. Go to the same settings page, return to main menu hitting Escape.
5. Go to the same page for the 3rd time. Settings are set to "never".

#### Expected behavior
Settings preserved.

#### Screenshots

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment] 2024-02-09 15:39
Radio buttons are the most annoying GUI element since textarea editing has been implemented.
Pressing escape and clicking on cancel are not necessarily the same, but I can't think of how this would be a problem here.
What is important is whether the actual values in gem-balduri.ini remain sane. IOW is it just a display problem or does data get corrupted?

**Comment by burner1024** [comment] 2024-02-09 16:59
Values get reset to 1.

**Comment by burner1024** [comment] 2024-02-20 09:01
Looks like it was supposed to be fixed in #1823 but wasn't.

**Comment by bsdcode** [comment] 2024-02-26 00:22
This bug affects RADIOBUTTON controls in general. There is also the `BitsPerPixel` option in the graphics option window which suffers from the same problem. There the value can get reset to `32`. It seems the erreonous reset-value is the value from the highest `button_id` inside one `name_id` group:
https://github.com/gemrb/gemrb/blob/d0af7b1c9952e00489cfe0c39056760eb0e8c3dd/gemrb/GUIScripts/GUIOPT.py#L129-L133
https://github.com/gemrb/gemrb/blob/d0af7b1c9952e00489cfe0c39056760eb0e8c3dd/gemrb/GUIScripts/GUIOPT.py#L231-L236

So it looks like when the bug hits, the program is at the highest `button_id` and writes its `value` back then.

I also discovered that the bug affects only button groups which you don't change. Example: you change the `Command Sounds Frequency` from `Seldom` to `Always` but leave `Selection Sounds Frequency` at `Seldom`, then Command will be set correctly to `Always` and Selection will reset wrongly to `Never`.

So the bug is somewhere at saving the values back to the dictionary. Also `MarkDirty()` can be interesting.

**Comment by bsdcode** [comment] 2024-02-26 14:29
The root of the problem is a weird initialization sequence for the radiobuttons when opening an options window. If you trace `Button:SetState` and `Button:UpdateState` from gemrb/core/GUI/Button.cpp you discover what happens here (3=always, 2=seldom, 1=never):
```
Test for value 3:
    Test button 3: equal; set state to pressed; continue with next value
Test for value 2:
    Test button 3: not equal; set state to enabled;
    Test button 2: equal; set state to pressed; continue with next value
Test for value 1:
    Test button 3: not equal; don't change state because it's already in enabled state;
    Test button 2: not equal; change state from pressed to enabled
    Test button 1: equal; set state to pressed; finished
```
So whenever you open a window with radiobuttons on it, the last radiobutton in the list will get the state `pressed`. Only changes done afterwards are properly saved.

Now we need to find out which part is responsible for this initialization sequence.

**Comment by bsdcode** [comment] 2024-02-26 23:04
Ok, I come to the conclusion that this is just normal "GUI galore", yes values in dictionaries do get overwritten numerous times in short succession. Especially when all radiobuttons in one group read and write the same dictionary key.

I spend some time diving into the callstack
```
GUIOPTControls.OptRadio
GemRB_Control_SetVarAssoc
Control::BindDictVariable
Control::UpdateDictValue
```
and tried to untangle it, but in the end there's a really easy fix for this which builds on the previous fix:
https://github.com/gemrb/gemrb/blob/d0af7b1c9952e00489cfe0c39056760eb0e8c3dd/gemrb/GUIScripts/GUIOPT.py#L229-L243
Just add
```python
GemRB.SetVar('Command Sounds Frequency', frequency)
GemRB.SetVar('Selection Sounds Frequency', frequency2)
```
to it. I'll generalize it a bit and make a PR. Save the rework of the GUI framework with better radiobutton handling for the 2.0 release ;)

**Closed** 2024-02-27 15:44 UTC
Labels: bug, system: GUI
