### ISSUE TITLE
[bug] Fireball SPWI304 have reduced range 

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#145] opened 2019-05-01 01:06 UTC
Baldur's Gate 2/BGT. I compared on both original and GemRB engine. Fireball (SPWI304) have reduced reach on GemRB by about 71 pixels. Fireball uses _visual range of caster_ for range so it should also fix problems for other spells if they happen to have reduced range. Near Infinity list the range at 40 feet.

Original reach: 417.7 pixels
![Original Engine FireBall Range](https://user-images.githubusercontent.com/17316115/57002149-498b4180-6b8b-11e9-9bfb-0f6e8a9f23e3.jpg)
Other results on original engine:
418.6
412.1
411.4
415.8
427.0
425.1
422.2

GemRB reach: 346.1 pixels
![GemRB Firebal Range](https://user-images.githubusercontent.com/17316115/57002154-4f812280-6b8b-11e9-9169-b18d025066b6.jpg)

GemRB reach: 350.1 pixels (second try).
![GemRB fireballl reach](https://user-images.githubusercontent.com/17316115/57005656-b44a7600-6ba7-11e9-8990-b7c06decfea5.jpg)

P.S. I don't know how to diagnose it.  The GemRB frame rate at which fireball spreads around is faster than on original engine.  I noticed it when doing comparison tests.

**Comment by lynxlynxlynx** [comment] 2019-05-01 08:47
Hmm, it could be the range was capped to the visual range, so even though fireball has 40' in the projectile, it got degraded to 30'. That'd still be too much for both versions (16/12 px). But to make good comparisons, the shots have to be at the same angle, since the engine is isometric. Try with horizontal targetting and on something obvious, so it's easy to measure reliably later. Target outside of the visual range, so a caster move is forced.

The spread thing looks similar to me: https://youtu.be/K-CHpyDY_Co?t=173

**Comment by cygarniczka** [comment] 2019-05-06 15:17
Results from the original engine in pixels: 
425.0
419.0
426.0
421.1
420.0
425.0
419.0
420.0
424.1
424.0

The score for perfect horizontal is 420.0 I compared the screnshots and with 425 there is an angle of about less than 5 degrees.

**Comment by lynxlynxlynx** [comment] 2019-10-02 21:33
Hey, I'm looking at this, but it's still unclear. Can you also make a comparison with a modded spell, with a range of 30 and 20?

**Comment by caillean7** [comment] 2019-10-24 09:06
Sure - just so I get this right: Reduce the range in the spell abilities with NI, make screenshots and measure the range with GIMP for both GemRB and IE?

**Comment by caillean7** [comment] 2019-10-24 09:17
Alright - I'll get to it at the weekend at the latest.

**Comment by caillean7** [comment] 2019-10-27 15:56
While I've made those measurements to the best of my ability (the same unmodded BG2 with 1024 x 768 resolution used for both IE and GemRB), the GemRB ones proved to be a little difficult due to the pathfinding. You'd attempt to target a point beyond the spell's range to make sure you measure the max range, so the caster walks up to that target point until they're in range. On IE they walk a horizontal line, while on GemRB they immediately start in a diagonal. So I tried to target close to spell range so the caster would make just a step or two, still, the results divergence from the mean value quite a bit and are probably not too accurate. It might be worth repeating that one after #126 is merged? Still, the reach is way shorter on GemRB than on the original. With the 20 ft. fireball on IE the caster is well out of range of the AoE, while on GemRB they fry themselves. Here are the mean values:

**IE:** 20 ft. range ~309 px, 30 ft. range ~427,5 px
**GemRB:** 20 ft. range ~170 ft., 30 ft. 248,2 px

So this is even more off than what @cygarniczka had and probably not connected to visual range.

**Comment by lynxlynxlynx** [comment] 2019-10-27 18:10
Huh, your IE value for 30 is about the same as the ones before for 40. Do you get the same numbers for eg. 45 and 35?

We use 9 for the conversion, so our true values there should be 180 and 270. 20px is quite some variability though!

At least it's confirmed that the range matters, unlike with weapons.

**Comment by caillean7** [comment] 2019-10-27 18:23
I have actually no idea if game resolution matters here? I thought that my IE results for 30 ft. might be so close to cygarniczka's for 40 ft. because they use a different resolution.

**Comment by lynxlynxlynx** [comment] 2019-10-27 19:10
No, since it only shows more of the area.

**Comment by caillean7** [comment] 2019-10-27 19:29
> Do you get the same numbers for eg. 45 and 35?

I do get very similar numbers for all the ranges from 30 to 45 ft - dunno, I'm tired, perhaps I leave that until tomorrow and look at the screenshots again - btw. should I upload them for you?

**Comment by lynxlynxlynx** [comment] 2019-10-27 19:44
I just interpret it that it has an upper bound, probably of the visual range, which is 30 by default. Unfortunately only bg1 (totsc) and iwd2 have the SetVisualRange action, but bg2 has an effect:
https://gibberlings3.github.io/iesdp/opcodes/bg2tob.htm#op262

You could either repeat the experiment in bg1, to try to find a ceiling there and if there is one, run a script to increase the visual range and retry. In bg2 you'd have to create a separate spell first, but it's doable.

But we probably don't need such thoroughness. A simpler test is to have the caster be blinded by someone or something else, since that also reduces the visual range.

**Comment by caillean7** [comment] 2019-10-27 20:23
> I just interpret it that it has an upper bound, probably of the visual range, which is 30 by default.

When 30 is the visual range, it would make sense that the values are so similar. Huh, after this and the weird trap stuff the game makes me question my sanity. Well, even more than usually. I'll remeasure the screenshots again first thing tomorrow, though. Then, perhaps modifying some item to give a blindness effect could work.

**Comment by lynxlynxlynx** [comment] 2019-10-27 20:31
No need to remeasure without the item. Too bad there isn't a cursed scroll of blindness. Anyway, unless you're testing with a solo sorcerer, you could also just spawn a normal scroll of blindness and use that.

**Comment by caillean7** [comment] 2019-10-27 20:41
Heh, it would be pretty weird if a blind caster would mean a spell range of zero. Perhaps they have hardcoded the upper limit spell reach to default visual range somehow to avoid that.

**Comment by lynxlynxlynx** [comment] 2019-10-27 20:46
Blindness sets it to 2 ...

**Comment by caillean7** [comment] 2019-10-28 11:00
Still, very close to home. But indeed, my blinded mage had the fireball go off pretty much in front of her, so reducing visual range does affect spell range. I wanted to find out if it's also possible to enhance it, so I added that opcode 262 effect to the Amulet of Protection, tried both setting a new visual range and giving a bonus, but those modifications had no effect in game. With and without the amulet I could see equally far, and again the values ranges of the fireballs stay pretty much the same. So - dunno why this effect didn't do anything - either is there some hardcoded upper value or it just doesn't work on an item?

Well, we know that the spell range is affected by effects reducing the visual range of the caster, at least. Plus, the factor used to translate feet into pixels seems off? Question is, why are my results so different than cygarniczka's. The fonts and GUI elements look smaller on higher resolution displays, so could it be the screen resolution affecting this?

**Comment by caillean7** [comment] 2019-10-28 11:18
> The score for perfect horizontal is 420.0

I added some more measurements (15 values in total) and re-calculated the average value, which turned out to be 419,something, so I'd second that.

**Comment by lynxlynxlynx** [comment] 2019-10-28 11:21
Yes and spell descriptions are notoriously flaky. If we return to the results:
> IE: 20 ft. range ~309 px, 30 ft. range ~420 px
> GemRB: 20 ft. range ~170 px, 30 ft. ~248,2 px

The first factor would be 15.5, the second closer to 14. Should be one and the same, can you perhaps do more measurements with 20? Or maybe even 25, 15, just to get more factors, data.

**Comment by caillean7** [comment] 2019-10-28 14:12
KK, done. Those first values were from the center of the explosion to the center of the caster and therefore bigger than cygarniczka's, but I re-measured them from the center of the explosion to the tip of the caster's foot, all angels at exactly zero. 20 values for each range.

| spl. range              | avg. | conv. factor px/ft |
|-------------------------|--------|---------|
| 30 ft. / max range  | 422,6 | 14,09 |
| 25 ft.                      | 383,25 | 15,33 |
| 20 ft.                      | 303,75 | 15,19 |
| 15 ft.                      | 223,05 | 14,87 |

So I dunno if the variations in this conversion factors is acceptable. Maybe use 15 instead of 9? We can then re-test on GemRB, judging from what I saw yesterday probably best after the pathfinding is merged - if that's anytime soon?

Since yesterday I switched from pencil and paper to a spreadsheet, yay, it's included in the attached zip. Including the screenshots as well makes that archive way too big, so if you wanna see them I can upload them elsewhere?
[fireb_range_tests.zip](https://github.com/gemrb/gemrb/files/3779044/fireb_range_tests.zip)

**Comment by lynxlynxlynx** [comment] 2019-10-28 16:52
Hmm, good stuff. The confidence is pretty high, only affecting the factors to its second decimal (at 95% and assuming normality). 

But of course: WTF. Especially the 30ft value, since it's significantly decreased compared to others. The distance would have to be around 450 to net a factor around 15. Or the actual cap is at 28 "feet" ... oh right, I knew it sounded familiar (TLDR: it is 28!):
https://www.gibberlings3.net/forums/topic/29618-sr-revised-v110-2019-february-5th/?tab=comments#comment-262398

The expected value all along has been 16. Or 12 if we were shooting up/down, due to the isometric view. The way we currently use the factor, it has to use the higher number, since we don't have angle info at that point, so for a lot of orientation we would have greater range (well if it wasn't set to 9 now).

I've increased the factor, capped the range and tweaked the visual range. Tell me how it looks now.

TODO: proper distance calculation

**Comment by caillean7** [comment] 2019-10-28 17:29
> Hmm, good stuff.

Heh, usually people say that about booze, not statistics.

We're still a bit short, though that whole measuring is a bit wonky, as mentioned above. I tried to get shots with an angle of 5 at max, so it's not perfectly horizontal. Calculated an average of 407,4, IE has 422,6. Also, while the single values on IE are pretty homogeneous (between 420 and 424 px), the GemRB vary from 397,2 up to 411,4.

**Comment by bradallred** [comment] 2019-10-28 18:24
> since we don't have angle info at that point

at what point? If we have the source and target points that is easily calculated like we already do in  `Projectile::SetTarget` has angle calculation code in it. It appears we do need to fix it to properly adjust for isometric coordinates tho.

**Comment by lynxlynxlynx** [comment] 2019-10-28 18:36
That's only one user, the rest are simpler personal distance checks, but yeah, I'm looking into it.

@caillean7: Yea, I set it to 15, not 16.

**Comment by lynxlynxlynx** [comment] 2019-10-31 09:10
@caillean7 just for verification, please do a short test with any lower range (<=28), but now targetting vertically. Doesn't need many repeats.

**Comment by caillean7** [comment] 2019-11-01 10:51
I tested with a 20 ft range just 5 or 6 times each, it seems our reach when targeting vertical is quite a bit higher than on IE: average is ~242 px on IE, ~287 px on GemRB.

**Comment by lynxlynxlynx** [comment] 2019-11-01 10:58
Perfect, it all adds up, thanks!

**Comment by lynxlynxlynx** [comment] 2019-11-02 20:43
Ok, I've added a handy function to adjust the range, but just used it for the obvious lightning-bolt style projectiles part. There's way too many users on the main path for me to be comfortable changing this just before release, ergo I'm postponing the rest of the changes. The bump of the constant pretty much already fixed the bug — overfixed in the player's favor.

**Closed** 2022-01-18 16:31 UTC
Labels: bug

**Comment by MarcelHB** [comment] 2024-09-29 15:00
There is still something too reduced, at least for IWD2. Let's say I line up my 5 PCs like this, and make the center one target of the fireball. In the original, this makes all of them hit:

![iwd2_fireball](https://github.com/user-attachments/assets/6b2cec82-beb0-4e84-8951-f0deb20c6b59)

In GemRB, the radius never gets past the PC directly to the left or right.

**Comment by lynxlynxlynx** [comment] 2024-09-29 15:11
It was  reduced in iwd2, but apparently too much. The test was with the goblin shaman leading the attack on Targos — his fireball at the main entrance (last stage of the attack) didn't hit the two useless guards besides him.
