### ISSUE TITLE
[iwd1] skill point inconsistency  

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1338] opened 2021-07-04 10:19 UTC
#### Bug description
there is some inconsistency with skill point.

you can see in screenshot wrong skill point number. And some class seems to have some skill points (I don't think they should have).

#### Screenshots
record before level up for a bard
![bard_before_levelup](https://user-images.githubusercontent.com/55502325/124381170-5226b780-dcc1-11eb-8996-a155423eb78a.png)

point displayed during level up
![bard_levelup](https://user-images.githubusercontent.com/55502325/124381180-5eab1000-dcc1-11eb-88fa-f975f655fd17.png)

point after level up
![bard_after_levelup](https://user-images.githubusercontent.com/55502325/124381192-68cd0e80-dcc1-11eb-8dac-6d4dd79e0f34.png)

paladin
![paladin](https://user-images.githubusercontent.com/55502325/124381265-dc6f1b80-dcc1-11eb-8b29-f32e6418aaf1.png)

ranger
![ranger](https://user-images.githubusercontent.com/55502325/124381268-e133cf80-dcc1-11eb-967c-155515f9f27f.png)

druid
![druid](https://user-images.githubusercontent.com/55502325/124381271-e6911a00-dcc1-11eb-9315-4fde9db6cd63.png)

mage/thief (this one seems normal)
![mage-thief](https://user-images.githubusercontent.com/55502325/124381290-fdd00780-dcc1-11eb-9bd5-b21ad6535df2.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment] 2021-07-04 12:34
Those are racial bonuses, though something is indeed wrong in the levelup combo.

**Comment by lynxlynxlynx** [comment] 2021-07-11 07:10
Do you have a save with this bard unleveled? Or at least which level was she at beforehand?

**Comment by FrElvire** [comment] 2021-07-13 05:22
Unfortunately, I don't have a save before, but the bard was at level 11 before level up.

But i have a save before a fighter level where skill points (racial bonus) weren't displayed when leveling up if you will?

![image](https://user-images.githubusercontent.com/55502325/125395010-dc9aa580-e3aa-11eb-96cc-c4d9bc2b5ba5.png)

**Comment by lynxlynxlynx** [comment] 2021-07-27 11:36
Then closing as a duplicate of #435.

**Closed by lynxlynxlynx** 2021-07-27 11:36 UTC
Labels: bug, game: iwd1, system: GUI
