### ISSUE TITLE
 [macOS] App must be run from the /Applications folder, or else it fails

### ISSUE THREAD

**Issue by shinra-electric** [gemrb/gemrb#1580] opened 2022-03-03 17:08 UTC
#### Bug description
GemRB will not run if the app bundle is not in the /Applications folder. 

If it is in /Applications, it works fine. 

If it is in (for example) /Applications/Games or any other folder it will fail. 

#### Steps to reproduce
1. Move GemRB to any folder other than /Applications. 
2: Try to load a game

#### Screenshots
![Screenshot 2022-03-03 at 16 58 27](https://user-images.githubusercontent.com/50119606/156614701-ea7fd22e-2ccf-4ca1-b5f4-e33a967984c1.png)
[GemRB.log](https://github.com/gemrb/gemrb/files/8179597/GemRB.log)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by shinra-electric** [comment] 2022-03-03 17:10
Looking at the log, it seems to be the plugin manager 

`[PluginMgr/]: Loading Plugins from /Applications/gemrb.app/Contents/Plugins`
`[PluginMgr/ERROR]: Plugin Directory (/Applications/gemrb.app/Contents/Plugins) does not exist!`

**Comment by bradallred** [comment] 2022-03-03 17:11
yeah, we should use relative paths more, but you can work around it by deleting the app preferences and relaunching from the new directory.

**Comment by shinra-electric** [comment] 2022-03-03 17:32
Hmm, can you confirm which preferences file?  I have deleted ~/Library/Preferences/org.gemrb.gemrb.plist and it doesn't seem to make a difference....

**Comment by bradallred** [comment] 2022-03-03 17:35
im not sure, I would think that would be it, but we positively don't hardcode the /Applications prefix anywhere. I build and run with Xcode all the time and obviously that doesn't run from /Applications.

**Comment by shinra-electric** [comment] 2022-03-03 17:37
I built with cmake, do you think that might have had an effect?

**Comment by bradallred** [comment] 2022-03-03 17:39
possible, I cant test it because I haven't been able to build with cmake in ages now due to #1329

**Comment by bradallred** [comment] 2022-03-03 17:45
I haven't been able to reproduce this with an Xcode build, but I'm still not sure how the two would differ in any meaningful way. Could be that there is a `#define` that is set via cmake, but not Xcode.

**Comment by lynxlynxlynx** [comment] 2022-03-03 18:30
As a linux user, it seems to me like the gemrb config stays the same, so all the default paths are used. Can the cfg not be edited?

**Comment by bradallred** [comment] 2022-03-03 18:35
there is no cfg on Mac because everything needs to be in a bundle. 

it looks like cmake sets these:
```
--   PLUGIN_DIR: /Applications/gemrb.app/Contents/Plugins
--   BIN_DIR: /Applications
--   DATA_DIR: /Applications/gemrb.app/Contents/Resources
--   MAN_DIR: 
--   SYSCONF_DIR: 
--   DOC_DIR: /Applications/gemrb.app/Contents/Resources
```

so they are probably getting hardcoded via a `#define`. The Mac build should just not set these.

**Comment by bradallred** [comment] 2022-03-03 18:48
there is no point in configuring something what is necessarily unmovable. plugins must live in the `Plugin` directory of the bundle in order to be loaded. We are clearly borking this by hard coding:

```
#ifdef PLUGIN_DIR
	CONFIG_PATH("PluginsPath", config.PluginsPath, PLUGIN_DIR);
#else
	CONFIG_PATH("PluginsPath", config.PluginsPath, "");
	if (!config.PluginsPath[0]) {
		PathJoin(config.PluginsPath, config.GemRBPath, "plugins", nullptr);
	}
#endif
```

MacOS should be in the `#else`, but is not when built with cmake.

same thing, but even worse for `DATA_DIR`:

```
// build time supplied directory first
#ifdef DATA_DIR
	strlcpy(outPath, DATA_DIR, maxLen);
#else
	#ifdef __APPLE__
	CopyBundlePath(outPath, maxLen, RESOURCES);
	#else
	// check $GEM_DATA env. note that Android wrapper sets this.
	char* dataDir = getenv("GEM_DATA");
	if (dataDir) {
		strlcpy(outPath, dataDir, maxLen);
	} else {
		if (!CopyHomePath(outPath, maxLen)) {
		#ifdef WIN32
			strlcpy(outPath, ".\\", maxLen);
		} else {
			PathAppend(outPath, PACKAGE);
		#else
			strlcpy(outPath, "./", maxLen);
		} else {
			PathAppend(outPath, "."PACKAGE);
		#endif
		}
	}
	#endif
#endif
```

we clearly have Apple specific code in the `#else` on this one

**Comment by lynxlynxlynx** [comment] 2022-03-03 18:56
I disagree that it's pointless, since adding a config would enable us to remove part of this ifdefing. Why special case the code when it can be dictated by data?

**Comment by bradallred** [comment] 2022-03-03 19:26
I dont think you understand, that `#ifdef` has _nothing_ to do with Mac. Mac wants to be in the non hardcoded `#else` case. I do not know why we have hardcoded paths at all, but it certainly has nothing to do with macOS.

**Comment by lynxlynxlynx** [comment] 2022-03-03 19:30
These are fallback so config files are not always needed, so it's the `#else` parts that should be removed where possible. That's why I'm suggesting a config, since you want to override the default behaviour.

**Comment by bradallred** [comment] 2022-03-03 19:32
this makes no sense. defining `DATA_DIR` _is_ hardcoding the path at compile time! By your own logic of how windows does it the `#else` path is what you are suggesting.

**Comment by bradallred** [comment] 2022-03-03 19:39
I assume you are talking about other `#ifdef`s (`#if TARGET_OS_MAC`) that have nothing to do with this issue. I wont disagree that those should be removed, but we dont need to have a `GemRB.cfg` to do that. We already construct and popular an `InterfaceConfig` at runtime. we can put whatever paths in it that we want.

**Comment by bradallred** [comment] 2022-03-03 21:01
@shinra-electric can you verify that this issue is now fixed for you?

**Closed** 2022-03-03 21:00 UTC
Labels: bug

**Comment by shinra-electric** [comment] 2022-03-03 21:36
Yes, I was able to launch a game from ~/Downloads. 

Thanks

**Comment by lynxlynxlynx** [comment] 2022-03-03 22:35
Re DATA_DIR: yes, of course it's hardcoding, I never disputed that. But it's just the fallback value. Windows doesn't reach that `#else` unless one whips up their own build system, so for all intents and purposes that code is non-reachable and can be removed. I'll reorder it a bit, since if we're taking env vars, they should have precedence. The function was never adapted to take into account custom InterfaceConfigs.

**Comment by bradallred** [comment] 2022-03-03 23:01
we shouldn't be using `DATA_DIR` or any other define for specifying paths tho. Any esoteric platform that requires a hardcoded path can easily specify such a path by writing that path to the `InterfaceConfig` prior to calling `core->Init(config)` in their own `GemRB.cpp` rather than setting a path in cmake.

> The function was never adapted to take into account custom InterfaceConfigs.

I dont know what you mean by this, all platforms have instantiate an `InterfaceConfig` and it's completely transparent to the inner workings of `Interface`. Most just create one from `GemRB.cfg`, but there is no difference between that and one that is populated at runtime as far as `Interface` is concerned.

IMO `Interface` shouldnt even be using env vars. Just inject them into the `InterfaceConfig` so we dont need all these branches in the core.

we should open a new issue to resolve this separate matter.
