### ISSUE TITLE
 iwd1 broken pathing in ar1008 (Snowdrift Inn)

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1819] opened 2023-06-25 16:57 UTC
#### Bug description
Characters are unable to access the two lower rooms in the Snowdrift Inn map (ar1008)

#### Steps to reproduce
Enter the Snowdrift Inn, move characters to the upper room, works normally.
Attempt to enter the lower rooms and the selection circle appears momentarily and then disappears as if the path is obstructed.  
The doorway shows the "not possible" cursor on the floor for both lower doorways, perhaps a door flag is set, the walkmesh is broken or some other pathing issue.

#### Expected behavior
In the vanilla game the doors are open and the rooms may be entered freely.

#### Screenshots
Screenshot showing the cursor in the open doorway of one of the lower rooms.
![Screenshot from 2023-06-25 14-17-14](https://github.com/gemrb/gemrb/assets/137374871/a9dda324-405b-4f39-891e-be30a8d1c44b)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)

- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment] 2023-06-25 18:21
![image](https://github.com/gemrb/gemrb/assets/121515/3ce624e1-6a16-4cd1-b0cc-d512cb0814f3)
A duplicate of #1015

**Closed by lynxlynxlynx** 2023-06-25 18:21 UTC
Labels: bug, game: iwd1, system: pathfinding
