### ISSUE TITLE
[HOW] `itemdata.2da` not found

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#763] opened 2020-05-27 16:51 UTC
#### Bug description
During GemRB initialization following error is logged:

```
[Core]: Initializing Inventory Management...
[ResourceManager]: Found 'itemtype.2da' in 'GemRB Unhardcoded data'.
[ResourceManager/ERROR]: Couldn't find 'itemdata.2da'.
```

Skimming through code, I found information it is only required for IWD2 (and indeed such file was added to unhardcored data. It's more improvement rather than a bug, to not try to load/hide error for HOW (and possibly other games).

There are more files that are not found, possibly for the same reasons (`'WMAPLAY.2da` apparently is present only for PST, `wildmag.2da` for BG2, etc.).

GemRB version: 0.8.6-git

#### Steps to reproduce
1. Start HOW
2. See error logged on console

**Comment by lynxlynxlynx** [comment] 2020-05-27 21:06
That's perfectly fine. Closing as a duplicate of #533

**Closed by lynxlynxlynx** 2020-05-27 21:06 UTC
Labels: bug
