### ISSUE TITLE
Slow as hell during draconis battle (not even playable)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#890] opened 2020-08-01 16:03 UTC
#### Bug description
During battle with draconis when displayed, gemrb take 100% CPU on one core and become very slow <2FPS (see fps counter on video)

Can this be tied to new pathfinding code ? : 

ResourceManager]: Searching for 'mdr1_br1'...                                                   
[ResourceManager]: Found 'mdr1_br1.bmp' in 'chitin.key'.                                         
[FindPath/DEBUG]: s = (665, 1325), d = (614, 1355), caller = Draconis, dist = 7, size = 7        
[FindPath/DEBUG]: Pathing failed for Draconis                                                    
[ResourceManager]: Searching for 'mdr1_br1'...                                                   
[ResourceManager]: Found 'mdr1_br1.bmp' in 'chitin.key'.                                         
[ResourceManager]: Searching for 'mdr1_br1'...                                                   
[ResourceManager]: Found 'mdr1_br1.bmp' in 'chitin.key'.                                         
[FindPath/DEBUG]: s = (665, 1325), d = (631, 1345), caller = Draconis, dist = 7, size = 7        
[FindPath/DEBUG]: Pathing failed for Draconis                                                    
[ResourceManager]: Searching for 'mdr1_br1'...                                                   
[ResourceManager]: Found 'mdr1_br1.bmp' in 'chitin.key'.                                         
[ResourceManager]: Searching for 'mdr1_br1'...                                                   
[ResourceManager]: Found 'mdr1_br1.bmp' in 'chitin.key'.                                         
[InitRound]: Name: Invisible Stalker | Attacks: 1 | Start: 45685299                              
[Actor/DEBUG]: Performattack for Invisible Stalker, target is: Skeleton Warrior                  
[Attack/COMBAT]: (Main) Left: 0 | Next: 45685389 [Missed]                                        
[FindPath/DEBUG]: s = (665, 1325), d = (665, 1325), caller = Draconis, dist = 7, size = 7        
[GameScript]: Displaying string on: bazdra02                                                     

GemRB version: master

#### Steps to reproduce
1. load save
2. go close enough to the dragon to see it

[000000032-draconis battle.zip](https://github.com/gemrb/gemrb/files/5010901/000000032-draconis.battle.zip)

#### Expected behavior
No slowdown

#### Video
[slow.zip](https://github.com/gemrb/gemrb/files/5010887/slow.zip)

**Comment by lynxlynxlynx** [comment] 2020-08-01 18:53
I almost gave up on reproducing, but then it happened when I ctrl-y-ed the dragon form.

In my case, even the human Draconis (ar6000) didn't move (is that expected? @frelvire) with failures of pathfinding. On transformation, he got stuck with one of the stalkers (and neither were able to move, of course):
https://i.imgur.com/ASqhXdM.png

Once the slowdown started, I ctrl-c-ed, so perhaps that's not the main culprit, but it did break right on pathfinding again (Map::IsWalkableTo). @kmfrick can you take a look? We definitely need to fix the different circle sizes not adjusting position correctly, but it's not clear yet that's enough (human form).

**Comment by FrElvire** [comment] 2020-08-02 10:22
didn't notice problem with human dracons (yes he doesn't move but no slowdown, should he move ?) and at transformation I have killed all stalker before, so he doesn't get stuck immediatly

**Comment by lynxlynxlynx** [comment] 2020-08-02 10:34
I suspect he summons one of them in his spot immediately and it's just not obvious until he's in his dragon form.

**Comment by lynxlynxlynx** [comment] 2020-08-02 10:44
Yeah, he specifically creates them on himself (`CreateCreatureObject("STALKE",Myself,0,0,0)`). Also obvious we don't adjust the position if he transforms while pcs are near. If it wasn't for the wing buffet, they'd likely get stuck as well.

CreateCreatureCore needs an adjustment in its CC_CHECK_IMPASSABLE handling. (CC_CHECK_OVERLAP has always been unimplemented)

**Comment by kmfrick** [comment] 2020-08-02 10:44
Human Draconis moves for me. Managed to reproduce the slowdown, and a weird behavior: between pathfinding fails, dragon Draconis started moonwalking. Investigating.

**Comment by kmfrick** [comment] 2020-08-02 11:51
Yeah it's the fact that `IsWalkableTo` calls `GetBlockedInRadius` which, considering the actor's considerable size, repeats the same searchmap check a metric ton of times. Using `GetBlockedNavmap` instead fixes this and seems to work well, I'll open a PR and do some more testing.

**Comment by kmfrick** [comment] 2020-08-02 12:16
Hmm. It's very hard to reproduce by ctrl-q-ing dragon Draconis and moving him around, he seems able to pathfind quite well. I'll do some testing with the old pathfinder to see what's new and what the behavior was.

**Comment by lynxlynxlynx** [comment] 2020-08-03 21:30
I've stepped through the CreateCreatureObject call. Since it has 0 parameters, it spawns directly on the spot of the caller/caster, however the SetPosition/AdjustPosition call does not bump it out of the blocked space. Looks like it can't handle both radii to be 0; the first AdjustPositionX call immediately returns true. For some reason the searchmap square is marked as PATH_MAP_PASSABLE, though the 0 radii mean no adjustment happens.

**Comment by kmfrick** [comment] 2020-08-03 21:52
I noticed the dragon isn't consistently blocking the searchmap. Investigating this tomorrow morning!

**Comment by lynxlynxlynx** [comment] 2020-08-03 22:01
My testing was with the human form though. But it gave me an idea — these actors are preplaced and haven't moved, so perhaps we don't set their tiles to blocked for some reason. When I teleport closer, he doesn't have the squares drawn:
![image](https://user-images.githubusercontent.com/121515/89231289-4defa700-d5e5-11ea-8ce6-2117e674ab94.png)

Same is visible in the iwd bug. But it's inconsistent, as in the bg2 testing tavern some npcs do get their blocks drawn immediately (= recruitables) and some don't, only later. Could be just a debug drawing problem though.

**Comment by kmfrick** [comment] 2020-08-04 11:18
@FrElvire I can't reproduce the slowdown after applying #894, but maybe I just don't know the fight well enough to catch some corner case that triggers this. Can you recheck whenever you have time? I'll test some more in the afternoon, too.

**Comment by FrElvire** [comment] 2020-08-04 12:28
Just tested with your los-slim-check branch, no slowdown but as seen in in screenshot no squares drawn, Anomen and Draconis seems to be at the same place

Many "Draconis can't fit in destination"
[draco_fit_dest.txt](https://github.com/gemrb/gemrb/files/5022050/draco_fit_dest.txt)

![draco_fit_dest](https://user-images.githubusercontent.com/55502325/89293529-5cc67000-d65e-11ea-8507-b5713a61843d.png)

**Comment by kmfrick** [comment] 2020-08-04 13:09
By "no squares drawn" do you mean the ground circle or the searchmap occupying spaces with ctrl+8?

**Comment by kmfrick** [comment] 2020-08-08 08:46
I'm having issues reproducing the ground circles bug. Does it start out drawn and then disappear, or does Draconis transform with the ground circle not drawn?

**Comment by lynxlynxlynx** [comment] 2020-08-08 11:53
It's not related to pathfinding anyway. Just noting here that I'm in the process of fixing another inventory crash with the recent changes — made obvious by the illusion casting from Draconis.

**Comment by lynxlynxlynx** [comment] 2020-08-08 16:19
I can reproduce the vanishing circle, seems to happen sometimes at the edges. Just a graphical glitch though, since you can still target normally.

However, even with the PR applied, I can still both get the dragon to be stuck on a stalker and if it wasn't for the wing buffet, likely the same thing would happen with nearby attacking pcs. For the transformation, the ChangeAnimation action is used (so any changes need to be in ChangeAnimationCore). And the cutscene kills everybody it can except for the party with a forced spell right after that. So I guess there's also some unfortunate timing involved.

**Comment by lynxlynxlynx** [comment] 2020-08-15 08:33
I've got a fix/workaround for the getting-stuck part. I don't know what the original did, but displacing the new actor seems ok, since it's done in a cutscene.

**Closed** 2020-08-17 20:37 UTC
Labels: bug, performance, system: core
