### ISSUE TITLE
[subviews] Colors on Amnish soldier wrong in certain positions

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#635] opened 2020-02-18 08:09 UTC
**Describe the bug**
As you watch the Amnish soldier, you'll see that in certain positions his colors flip out. I'm not very famliar with terminology to be sure how to put it, but I hope screenshots convey enough.

This happens on subviews branch only, master is fine.

I would provide a savegame, but this is a modded install. Let me know if you need one from vanilla.

**To Reproduce**
1. Go to Den of Seven Vales
2. Watch Amnish soldier running around. His colors will flip.

**Expected behavior**
Consistent, not flipping colors.

**Screenshots**
Flipped
![Captura de pantalla de 2020-02-18 15-00-17](https://user-images.githubusercontent.com/1279852/74715680-8847d080-525f-11ea-87b8-35aa438dcba8.png)
Proper
![Captura de pantalla de 2020-02-18 15-00-40](https://user-images.githubusercontent.com/1279852/74715690-8c73ee00-525f-11ea-9d5c-ee8da58eaa76.png)

**Comment by MarcelHB** [comment] 2020-02-18 20:57
No, it's fine. We have observed this in different situations and vanilla games on subviews already (example in #399).

**Comment by burner1024** [comment] 2020-02-19 02:23
ok cool

**Comment by bradallred** [comment] 2020-03-15 17:31
Let's leave this open. I never got around to creating an issue for it and probably wont get around to working on it anytime soon.

**Comment by bradallred** [comment] 2020-03-22 05:31
I believe this is fixed now. recheck?

**Comment by burner1024** [comment] 2020-03-22 11:26
Not building for me, even with -DDISABLE_WERROR=1:
```
[ 14%] Building CXX object gemrb/core/CMakeFiles/gemrb_core.dir/IndexedArchive.cpp.o
In file included from /tmp/gemrb/gemrb/core/Sprite2D.h:35:0,
                 from /tmp/gemrb/gemrb/core/ImageWriter.h:23,
                 from /tmp/gemrb/gemrb/core/ImageWriter.cpp:19:
/tmp/gemrb/gemrb/core/Palette.h:99:64: error: ‘uint8_t’ has not been declared
  void CopyColorRange(const Color* srcBeg, const Color* srcEnd, uint8_t dst);
                                                                ^~~~~~~
```

**Comment by bradallred** [comment] 2020-03-22 15:25
if that was the inly error it should be fixed now too

**Comment by MarcelHB** [comment] 2020-03-22 16:19
Cannot reproduce it anymore.

**Comment by bradallred** [comment] 2020-03-22 23:25
Thanks!

**Closed by bradallred** 2020-03-22 23:25 UTC
Labels: subviews, system: animations

**Comment by burner1024** [comment] 2020-03-23 02:52
Confirmed, doesn't happen anymore.
