### ISSUE TITLE
Helmet drawing regression 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1512] opened 2022-01-02 16:56 UTC
While working on #1510 I noticed nobody has a helmet drawn. It's visible on the main char with the save from #1511. If you exit the area, also with the two approaching actors in the cutscene.

It worked at 0.9.0 release time, but I haven't pinpointed down at which time it got broken.

**Comment by bradallred** [comment] 2022-01-02 17:05
this is a dupe of #1365

**Closed** 2022-01-02 17:07 UTC
Labels: bug, system: core
