### ISSUE TITLE
[bug] BG2: Immediate invisibility when hiding in shadows

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#332] opened 2019-10-11 15:11 UTC
Split from #171:

**Description**
(Original-except it shouldn't happen on failure) hiding in shadows makes you invisible immediately (before the per-round roll)

Hiding is part of so called modal actions. You can look at the modal struct in Actor.cpp to see how they work in general. They're triggered through GUIScript.cpp, as the buttons get pressed, and Actor::TryToHide has the main rolling for deciding success. I'd start there to see why failure is not handled properly.

**Comment by ifyGecko** [comment] 2019-10-23 04:33
I should have a copy of iwd1&2 any day now, I can work on this when they arrive.

**Comment by lynxlynxlynx** [comment] 2019-10-23 09:48
Cool, thanks. Comment here if you get into trouble. IWD1 will be the better choice for debugging this, since the nomenclature will be more familiar.

**Comment by ifyGecko** [comment] 2019-10-25 04:02
This issue is due to light and is not consistent, sometimes the variable of "lightness" in Actor::TryToHide is assigned a value of 0 right outside "Winter's Cradle Tavern" in iwd. When the issue does not present itself "lightness" gets a value of 100.

Variables when the bug arises:
lightness: 0
light_diff: 37675114
Chance: 39182171

I have a hackish work around by setting "lightness" to 100 if it is 0 before calculating "light_diff" but this is not satisfactory. I will continue by looking into why GetLightLevel sometimes returns 0 instead of 100.

**Comment by lynxlynxlynx** [comment] 2019-10-25 07:12
Sounds like a different issue, though it makes sense to ensure light_diff doesn't underflow like that.

Returning 0 is valid, that's from data directly. It looks like ar1000lm.bmp (the lightmap) has high enough values though, so just step through GetLightLevel to see which part of the calculation/data is suspect.

**Comment by ifyGecko** [comment] 2019-10-25 20:11
In the if(tint) block c.r-tint->r, c.g-tint->g, and c.b-tint->b each are returning 0 so the calculation for lightness returns 0. I have poked around a small bit to try and see how a lot of the code involved is working but I am lost as to where to look for r-tint, g-tint, and b-tint.

**Comment by ifyGecko** [comment] 2019-10-25 21:19
The tint returned in GetLightLevel is FogTint, rgb=ffffff, and the color returned from GetPixel is also ffffff so the c.r - tint->r calculation and so on will be zero which is why GetLightLevel returns zero.

I am not sure as to why things are calculated the way they are regarding lightness when a tint is applied, could someone give some clarity on the if(tint) block in GetLightLevel?

**Comment by MarcelHB** [comment] 2019-10-25 22:21
We could calculate c.x - (255 - tint->x), which looks acceptable given the formula weights and the fact that many of the tint specifications are set to `0x80` anyway. And no more 0 in case of fog.

The constants look like a quick RGB to lightness calculation model, not sure which one.

**Comment by bradallred** [comment] 2019-10-25 23:24
the `tint` is for night time in IWD2 and perhaps others.

Some games (BG2 I think) have different maps for day and night so the builtin light map can be checked for hide in shadows. IWD2 doesn't have that, so it needs to check the tinted value instead.

**Comment by ifyGecko** [comment] 2019-10-26 01:09
@bradallred To make sure I got what your saying, Not all ie games can directly check the light map for lightness and that is why the tints exist?

@MarcelHB I have tried your suggestion and it seems to work with out a hitch. I will test the lightness value in a few more places in iwd to get complete validation.

If anyone knows the RGB to lightness model used like @MarcelHB mentioned or if it is not such a thing, could you fill me in on any details? A lot of concepts that are used in this project are completely foreign to me so any bit of information will go a long way.

**Comment by lynxlynxlynx** [comment] 2019-10-26 18:18
The tint exists for other purposes (time of day and weather adjustments), as noted in the comment in GetLightLevel. Also dream areas use it to spice things up. Timestop on the other hand just has a different drawing mode and doesn't use tint.

Not all the tint color components are at 0x80 or 0xff, so Marcel's solution would require further tweaking to maintain the color. It's easier to just make FogTint not be pure white.

**Comment by MarcelHB** [comment] 2019-10-26 18:31
As far as I see, `GetLightLevel` is effectively used by the `TryToHide` method only. And then I wasn't sure if hiding in the dream scenes is a thing at all. ;)

**Comment by ifyGecko** [comment] 2019-10-26 19:18
ok, thanks for the clarification. I did play around with a few new FogTint values before @MarcelHB mentioned the calculation adjustment but it didn't give useful results. When I get a chance I will mess around with some new values and a better calculation to use with those new values. If anyone knows why the calculation is the way it is, whatever concept that would dictate doing it that way, would greatly expedite the process for me.

**Comment by ifyGecko** [comment] 2019-10-26 19:31
Thanks for the clarification @lynxlynxlynx. I did play with some lower values for FogTint before @MarcelHB mentioned the calculation adjustment but they didn't produce anything useful, lightness = 5 and so on. It seems like the calculation needs to be changed in the if(tint) block even if FogTint is adjusted. I could be wrong so since I didn't explore it very far. 

I will continue by looking at better FogTint values and/or a better if(tint) calculation.

**Comment by lynxlynxlynx** [comment] 2019-10-26 19:36
This was all based on disassembled bg2 binaries, so the original behaved very similarly if not identically. We don't have any info on why FogTint is as it is, so that's more suspect, like I said.

**Comment by ifyGecko** [comment] 2019-10-26 19:59
Oh ok, I just wanted to make sure there wasn't a formula or known process I could study up on to make sure I was doing the calculation properly  or as close to as its suppose to be.

I didn't catch that you were saying there isn't known info on FogTint and that its suspect, my bad on that. However, I do not know if fog weather even works.

**Comment by lynxlynxlynx** [comment] 2019-10-26 20:58
You can force fog by running `ExecuteString('Weather(3)')` in our console. It just darkens everything slightly, so it doesn't look like fog at all. I didn't try that action in the original though (bg2 supports it).

It's so bad, so we can easily change the value without remorse. Maybe tinting is not good for a fog-like effect at all, since it needs to brighten.

**Comment by ifyGecko** [comment] 2019-10-27 22:02
@lynxlynxlynx I see what you mean about FogTint not being so good. A different way of applying fog would probably be better but I have this as a solution right now, https://github.com/ifyGecko/gemrb/commit/5b68705f46627a19455ed3efcee6cc957565b31c. I still need to test a few things out, maybe adjust the fractional scalar and/or the FogTint values.

**Comment by lynxlynxlynx** [comment] 2019-10-27 22:29
That's definitely wrong, now you're just averaging the two values.
I did some searching and Avenger said fog wasn't implemented in the original bg2 and I checked it does nothing in iwd2 either. SoD added proper fog, but it was met with utter disdain. 

So yeah, change the value to avoid the problem, nothing actually uses it. It shouldn't tint at all.

**Comment by ifyGecko** [comment] 2019-10-27 23:03
I haven't think any new values will work. Lower but still relatively high, white, values do not give much of a noticeable visual change but the lightness value ends up still being low, such as 5, which is wrong. If you keep lowering the FogTint values it just starts to darken the whole map which makes it visually wrong. It would be better to just remove FogTint all together at that point if nothing actually uses it, correct?

If not, the 1/2 was arbitrary I figured there was a better value or way to determine a value to describe the magnitude of the tint/shade. Which I ended up finding, using the same calculation but on RGBA colors allows you to control the scalar magnitude of the tint/shade by using the alpha channel of the color being applied. If you wanted FogTint to stay the lightness could be calculated with an alpha channel. That way if the calculation used throws off the tints that are proper and heavily used elsewhere they can be corrected with newer alpha channel values.

**Comment by lynxlynxlynx** [comment] 2019-10-27 23:21
I thought about something like full transparency `FogTint={0,0,0,0xff};`, but a glimpse at the code makes me think we ignore the tint's alpha channel. But maybe it's just the late hour.

**Comment by ifyGecko** [comment] 2019-10-27 23:45
It's not the late hour, you would be correct. I tried that a couple days ago. If you, anyone else, have any other ideas I am all ears, my only thought keeps going back to remove fog or adjust the calculation. I may just need to sit on this a few days and think about it in my spare time.

**Comment by ifyGecko** [comment] 2019-10-28 03:49
https://github.com/ifyGecko/gemrb/commit/40762b2143d80e660294ee0e2b91aed5ea3ee097 This is the best thing I can find to fix the issue. Using the alpha channel like I suggested previously started causing issues and adjustments to the calculation and tint alpha values to compensate didn't help. Considering nothing actually uses fog the simplest approach should just be to remove it instead of tweaking a lot of stuff around it which could just result in more issues later on down the road.

If this seems sufficient I will make a pull but if not give me some feed back and I will bring my fork's master back in line with gemrb/gemrb master and try again.

**Comment by ifyGecko** [comment] 2019-10-28 04:34
How about this for a fix? https://github.com/ifyGecko/gemrb/commit/c83c0c84b695a67ee0c60d073c58ce53c1d90708

**Comment by lynxlynxlynx** [comment] 2019-10-28 10:27
Much better, but only remove it from GetGlobalTint and Map::GetWeather (you can leave a comment with a TODO here, since we'll have to implement it at some point).

**Comment by lynxlynxlynx** [comment] 2019-10-28 19:42
I can't reproduce the original issue and the fog detour is now fixed, closing.

**Closed by lynxlynxlynx** 2019-10-28 19:42 UTC
Labels: bug, core, good first issue
