### ISSUE TITLE
IWD2: Everyone is hostile

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1622] opened 2022-05-29 19:04 UTC
#### Bug description
Something I just noticed, but only in IWD2: Whatever I load, even when starting a new game, every NPC around turns hostile. Interestingly, where applicable the dialog seems to pop up for a fraction of a second but disappears, with everyone red then.

#### Screenshots
![Screenshot_2022-05-29_21-01-00](https://user-images.githubusercontent.com/238558/170887293-05eb4a09-bdc9-446e-9091-88b63860790a.png)

Not sure if related, but there is only one tiny but suspicious line in the log:

```
[GameScript/ERROR]: ActionOverride failed for object and action:
[GameScript/DEBUG]: Int0: 0, Int1: 0, Int2: 0
String0: , String1:
Point: (0, 0)
1. Object: Brohn_Dead
2. Object - NULL
3. Object - NULL
RefCount: 2     actionID: 111
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

**Comment by lynxlynxlynx** [comment] 2022-05-29 20:09
I think this will turn out to be a dupe of #1621 since that also touches scripting in a significant way.

**Comment by bradallred** [comment] 2022-05-30 02:32
this appears fixed now

**Closed by bradallred** 2022-05-30 02:32 UTC
Labels: bug, game: iwd2
