### ISSUE TITLE
Can't open bag in store 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1440] opened 2021-08-18 05:25 UTC
#### Bug description
If I'm not misleading, in store you should be able to open bag to sell it's content. If you double click on a bag it doesn't show it's content but scrollbar go to bottom with many created empty slots.

Afterwards, empty slots stay in inventory.

#### Steps to reproduce
1. Go to store
2. Double click on bag

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/129841787-63aa4218-7855-4cd4-a4bb-74b28c3ca6fc.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment] 2021-08-18 06:15
This used to work. Are you saying that if you scroll up, you'll get to the bag items?

**Comment by FrElvire** [comment] 2021-08-18 10:02
Not exactly, if you scroll up you get inventory items and not bag items

**Comment by bradallred** [comment] 2021-08-18 14:02
kinda sounds like a dupe of #1439

**Comment by FrElvire** [comment] 2021-08-18 17:27
no even at commit ab16b86 it's the same. You don't notice it easily as scrollbar is at top. But in all case you don't have access to bag content

**Comment by lynxlynxlynx** [comment] 2021-08-20 19:58
Yeah, it's still broken, but slightly differently. It's clear something happens, as the store items get a different overlay and scrolling can get disabled, but the rest of the gui doesn't update properly, so you still see the same items on your side.

**Comment by FrElvire** [comment] 2021-12-30 05:43
I'm not sure if it's the same bug but now I can't even open a bag (not only in store) in IWD1

here is the log :

 [Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/GUISTORE.py", line 188, in OpenStoreWindow
[Python/ERROR]:     store_buttons = Store['StoreButtons']
[Python/ERROR]: TypeError: 'NoneType' object is not subscriptable

**Closed** 2022-01-24 18:37 UTC
Labels: bug, system: GUI
