### ISSUE TITLE
[bug] IWD1 w/o HoW: Hrothgar not initiating dialogue

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#417] opened 2019-11-23 08:49 UTC
**Description**
I'm following up on some things I noticed while testing the 2da updates I made recently. For IWD1 without the expansion installed Hrothgar doesn't start his initial talk at the beginning of a new game. He's just standing there. If you click on him, the dialogue starts okay. Tested on a fresh IWD1 installation with only the latest patch applied.

**GemRB version**
0.85-git

**To Reproduce**
- start a new game and import some random char
- click past the chapter text
- Hrothgar should not do his usual thing

**Expected behavior**
Have Hrothgar approach the party and start his dialogue

**Comment by MarcelHB** [comment] 2019-11-23 10:12
This is a duplicate of #353 with some helpful insights already collected there.

**Closed by MarcelHB** 2019-11-23 10:12 UTC
Labels: bug

**Comment by caillean7** [comment] 2019-11-23 10:40
Oooops...
