### ISSUE TITLE
[subviews] Some missing text centering in PST

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#293] opened 2019-10-05 19:29 UTC
In master, it looks as in the originals, but in subviews (without recognizing a structural pattern), some texts appear misaligned when center is expected. I found two occurrences so far:

1. The game menu (see screenshot) some buttons - the blue one looks good.
2. In the wizard/priest spell book where it says _Nth level_ between the pages.

![pst_main_menu_buttons](https://user-images.githubusercontent.com/238558/66259857-0fb40c00-e7b7-11e9-91d5-938859c69d56.jpg)

**Comment by bradallred** [comment] 2019-10-08 05:54
Are you sure the center flag is actually set? it looks like if it is then its not centered because it's a single word that has a break.

**Comment by MarcelHB** [comment] 2019-10-08 06:06
I don't know, I can check the GUIscripts then.

**Comment by bradallred** [comment] 2019-10-15 22:21
Looking at the history of `Font` on this branch everything looks unrelated. the only thing I saw as a potential candidate is 70eda9c and that was clearly added to fix a bug somewhere else. You can try reversing that change and at least identify if that is the cause.

I'm assuming the comparison of _all_ alignment flags (not just the center flag) between master and this branch is the same?

**Comment by MarcelHB** [comment] 2019-10-16 20:06
Revert that commit fixes the issue, yes.

Other than that, the flags in the GUI script looks untouched (`IE_GUI_BUTTON_MULTILINE`).

**Comment by bradallred** [comment] 2019-10-16 20:47
I meant the value of `align` in `font->Print( r, Text, ppoi, (ieByte) align );`, but if reverting that commit fixes it then it is moot.

reverting that commit of course isn't the right thing to do. We would have to look at the history around that to get a better idea of what exact use case it was fixing.

its possible that simply reordering these 2 if blocks would fix it without breaking the other:
```
if (eos && stop->w && wordW < stop->w ) {
	// its possible the last word of string is longer than any of the previous lines
	w = std::max(w, wordW);
}
if (stop->h && (LineHeight * (lines + 1)) > stop->h ) {
	break;
}
```

**Comment by bradallred** [comment] 2019-10-16 20:58
actually, probably not since it looks like we don't pass any metrics to the print call in `Button`.  That leaves the `else` case or passing metrics as the possible fixes. Still need to look and see what issue this was fixing to know what to check for regression.

I suspect deleting the else would fix this but break the other. I'm thinking passing the metrics is a good solution, but I don't know if that would cause issues in yet a 3rd unknown case. I think its unlikely to be a problem tho.

**Comment by bradallred** [comment] 2019-10-16 21:06
digging deeper its clear the metrics are never passed, only the sizing call allows them as a parameter. For printing they are determined by the `Region` we pass and if you look at the `Button` callsite there is clearly an unknown at play:

```
// FIXME: I'm unsure when exactly this adjustment applies...
r = Region( rgn.x + 5, rgn.y + 5, rgn.w - 10, rgn.h - 10);
```

so these number may not be accurate or may be different between games. The value `5` matches what we used to use for `TextArea` margins, so I'm not sure if that is where this comes from, but I changed the margins to `3` so maybe we need to change this to  `r = Region( rgn.x + 3, rgn.y + 3, rgn.w - 6, rgn.h - 6);`?

**Comment by MarcelHB** [comment] 2019-10-16 21:16
Your suggestion breaks another button:
![pst_btn](https://user-images.githubusercontent.com/238558/66959506-cee7ad00-f06a-11e9-8eeb-4ee170d70e2f.jpg)

I can look into further details tomorrow, hopefully.

**Comment by bradallred** [comment] 2019-10-16 21:19
Which one? :) changing the order of the ifs, or deleting the else?

**Comment by MarcelHB** [comment] 2019-10-16 21:20
Changing the region values.

**Comment by bradallred** [comment] 2020-03-26 16:28
looking at this again the `else w = std::max(w, wordW);` bit looks suspicious; we just barely set  `w` to another value (the value from before this commit where things work) in the previously executed statement above the `if`.

Does removing that fix this issue?

**Comment by MarcelHB** [comment] 2020-03-26 17:38
Hm, it makes no obvious difference.

**Comment by anewusername** [comment] 2020-08-30 04:34
Looks like `RenderText` uses `StringSize` to determine where to start printing the string (`linePoint.x`, passed to `RenderLine`), but `StringSize` now returns the size of the *widest* line, not the *first* one.

**Comment by MarcelHB** [comment] 2020-10-18 16:04
The sub-line/word break centering is not working, since one of the strings above is "Film- sequenzen".

```diff
diff --git a/gemrb/core/GUI/TextSystem/Font.cpp b/gemrb/core/GUI/TextSystem/Font.cpp
index 4a3d0d36d..18c8b433a 100644
--- a/gemrb/core/GUI/TextSystem/Font.cpp
+++ b/gemrb/core/GUI/TextSystem/Font.cpp
@@ -321,7 +321,7 @@ size_t Font::RenderText(const String& string, Region& rgn, ieByte alignment,
                                core->GetVideoDriver()->DrawRect(Region(linePoint + lineRgn.Origin(),
                                                                                                 Size(lineSize.w, LineHeight)), ColorWhite, false);
 #endif
-                               linePos = RenderLine(line, lineRgn, linePoint, canvas);
+                               linePos = RenderLine(line, lineRgn, linePoint, alignment, canvas);
                        }
                        if (linePos == 0) {
                                break; // if linePos == 0 then we would loop till we are out of bounds so just stop here
@@ -374,7 +374,7 @@ size_t Font::RenderText(const String& string, Region& rgn, ieByte alignment,
 }

 size_t Font::RenderLine(const String& line, const Region& lineRgn,
-                                               Point& dp, ieByte** canvas) const
+                                               Point& dp, ieByte alignment, ieByte** canvas) const
 {
        assert(lineRgn.h == LineHeight);

@@ -402,6 +402,14 @@ size_t Font::RenderLine(const String& line, const Region& lineRgn,

                StringSizeMetrics metrics = {lineRgn.Dimensions(), 0, 0, true};
                int wordW = StringSize(word, &metrics).w;
+
+               int lineAlignmentOffset = 0;
+               if (alignment & IE_FONT_ALIGN_CENTER) {
+                       if ((lineRgn.w - wordW) / 2 > dp.x) {
+                               lineAlignmentOffset = (lineRgn.w - wordW) / 2 - dp.x;
+                       }
+               }
+
                if (dp.x == 0 && metrics.forceBreak) {
                        done = true;
                        word.resize(metrics.numChars);
@@ -426,6 +434,8 @@ size_t Font::RenderLine(const String& line, const Region& lineRgn,

                        const Glyph& curGlyph = GetGlyph(currChar);
                        Point blitPoint = dp + lineRgn.Origin() + curGlyph.pos;
+                       blitPoint.x += lineAlignmentOffset;
+
                        // use intersection because some rare glyphs can sometimes overlap lines
                        if (!lineRgn.IntersectsRegion(Region(blitPoint, curGlyph.size))) {
 #if DEBUG_FONT
diff --git a/gemrb/core/GUI/TextSystem/Font.h b/gemrb/core/GUI/TextSystem/Font.h
index 55b2a8efc..438366e3a 100644
--- a/gemrb/core/GUI/TextSystem/Font.h
+++ b/gemrb/core/GUI/TextSystem/Font.h
@@ -163,7 +163,7 @@ private:
                                          Point* = NULL, ieByte** canvas = NULL, bool grow = false) const;
        // render a single line of text. called by RenderText()
        size_t RenderLine(const String& string, const Region& rgn,
-                                         Point& dp, ieByte** canvas = NULL) const;
+                                         Point& dp, ieByte alignment, ieByte** canvas = NULL) const;

        void SetAtlasPalette(PaletteHolder pal) const;
```
This way, it looks quite good already:

The only thing I see that gets lost is the handling of double spaces as break-helper: It's "Spiel  Laden" (Load) in constrast to "Spiel speichern" (Save) and "Zurück  zum Spiel" (Back).

**Comment by bradallred** [comment] 2020-10-20 06:28
it appears my `if` [reordering suggestion](https://github.com/gemrb/gemrb/issues/293#issuecomment-542884871) was never attempted? it seems to fix it for me. Does it break something else?

**Comment by MarcelHB** [comment] 2020-10-20 07:28
I'll look at it again later today.

**Comment by MarcelHB** [comment] 2020-10-20 19:47
That looks good, indeed. Not sure what I tested exactly back then.

Anyway, the only thing remaining now is what [I observed already](https://github.com/gemrb/gemrb/issues/293#issuecomment-542895053) for the blue/bluish buttons that contain a double-space.

**Comment by bradallred** [comment] 2020-10-20 19:55
I would tinker around near `wordBreak = line.find_first_of(L' ', linePos);` seems like we just need to expand `wordBreak` to the last space character.

**Comment by MarcelHB** [comment] 2020-10-20 20:46
I was wrong: The original does not do a line break there but simply swallows the 2nd space (and then it looks somewhat acceptable) ... I'm just not sure if it is a good idea to this globally. Maybe some there are some dirty text layout that rely on that?

**Comment by bradallred** [comment] 2020-10-20 20:51
no, everything in `TextContainer` is broken down into words and all whitespace is discarded completely. Go ahead and do it.

**Comment by bradallred** [comment] 2020-10-21 15:31
closing in favor of a new issue

**Closed by bradallred** 2020-10-21 15:31 UTC
Labels: game: pst, subviews
