### ISSUE TITLE
Menu music doesn't stop after loading a game

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1643] opened 2022-07-16 18:13 UTC
Seen in at least BG2 loading the attached save from the main menu. Happens every time and there is no error in the log.

it doesn't seem to happen for other saves, so i'm not sure if this is a save issue or an area issue (ar1401), but the save was made in gemrb, not the original.

[000000001-Quick-Save.zip](https://github.com/gemrb/gemrb/files/9126385/000000001-Quick-Save.zip)

**Comment by lynxlynxlynx** [comment] 2022-07-16 18:23
Works for me, can you attach the save?

**Comment by bradallred** [comment] 2022-07-16 18:33
save attached

**Comment by lynxlynxlynx** [comment] 2022-07-16 18:59
Can't reproduce with the save either. 🤷🏾‍♂️

**Comment by bradallred** [comment] 2022-07-16 19:04
do you know where the music is supposed to get stopped so I can debug it?

**Comment by lynxlynxlynx** [comment] 2022-07-16 19:12
Eventually Game::ChangeSong.

**Comment by bradallred** [comment] 2022-07-16 19:16
looks like we hit `if (IsStar(*poi)) return` in `Map::PlayAreaSong` so we bail out.

```
p *poi
(const GemRB::ieVariable) $1 = (str = "****")
```

**Comment by lynxlynxlynx** [comment] 2022-07-16 19:35
That could be intentional, since that's also how music is stopped by data (see songlist.2da)... I see I have different values in two installs though; one has P#BLANK.MUS instead... It's a fix from the Kivan mod, but the fixpack also does the same. I can reproduce with vanilla, but since we require the fixpack, let's just close this.

**Closed by lynxlynxlynx** 2022-07-16 19:35 UTC
Labels: bug, game: bg2, system: audio
