### ISSUE TITLE
[BG2] non-centered display on cutscene 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#749] opened 2020-05-24 14:39 UTC
#### Bug description
At start of TOB after killing the mage, select a windows (map, inventory,...) and wait pocket plane cutscene. If it doesn't crash (#748), screen is not centered on the cutscene

Note : I have already seen this bug before, not specific to this zone change

GemRB version: Master / SDL2

#### Expected behavior
Screen centered on cutscene

#### Video
[offscreen.zip](https://github.com/gemrb/gemrb/files/4673717/offscreen.zip)

**Comment by bradallred** [comment] 2020-05-26 16:12
I wonder if you would mind retrying on the other branch.

**Comment by FrElvire** [comment] 2020-05-26 18:25
Here is with the other branch, not identical to original but correct (after it's a question of preference).

[map_sub.mp4.zip](https://github.com/gemrb/gemrb/files/4684231/map_sub.mp4.zip)

**Comment by bradallred** [comment] 2020-05-26 18:29
ok, so it looks like it does work there? Is that correct?

If not, then is opening the map window actually part of producing this? seems if so then it is the map control that is overriding the viewport.

**Comment by FrElvire** [comment] 2020-05-27 09:23
Yes it works but contrary to original, the window (map or something else, spell, inventory,...) is not closed at zone change but at the beginning of the cutscene. (personally I prefer original behavior, do you want I try to make a video of original behavior to make up your mind  ?)

But yes there is not cutscene centring problem with your branch (so not concerned by this bug)

**Comment by lynxlynxlynx** [comment] 2020-05-27 09:53
No need, since we do need to close the window either way. I'm closing this issue, since it is a functional duplicate of #748.

**Closed by lynxlynxlynx** 2020-05-27 09:53 UTC
Labels: bug
