### ISSUE TITLE
[subviews] scrollbar activates by clicking anywhere in a window

### ISSUE THREAD

**Issue by fizzet** [gemrb/gemrb#1214] opened 2021-04-02 12:00 UTC
If you have a window with a scrollbar (say, GUILOAD), clicking anywhere in that window's area activates scrollbar behaviour (except on other controls).

**Comment by MarcelHB** [comment] 2021-04-02 12:26
Is it [that](https://github.com/gemrb/gemrb/issues/992)?

**Comment by bradallred** [comment] 2021-04-02 15:29
this is by design. mainly to support touchscreens, so I've no objection to moving it to a touch gesture instead.

**Comment by fizzet** [comment] 2021-04-03 08:51
I found it highly irritating to miss the button by a hair and find myself somewhere entirely different.

**Comment by bradallred** [comment] 2021-04-03 16:27
im sure touchscreen users feel similarly about trying to pinpoint a tiny scroll bar ;)

Regardless, now that we actually have touch gesture support it can be done that way instead.

however, this should only affect a mouse drag event so i'm not sure why you had that experience with a click. Could be something else at play if you want to investigate that.

**Comment by lynxlynxlynx** [comment] 2021-04-03 16:46
Can confirm the latest commit fixing guiload.

**Closed by lynxlynxlynx** 2021-04-03 16:46 UTC
Labels: bug, subviews, system: GUI
