### ISSUE TITLE
 [IWD1] Can't enter in rooms upstairs in kuldahar inn

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1100] opened 2020-12-12 15:01 UTC
#### Bug description
Character can't enter in rooms upstairs in kuldahar inn (Position: ar2115 [93.0]) except the last one.

GemRB version: master

#### Screenshots
![kuldahar_inn](https://user-images.githubusercontent.com/55502325/101987256-3ca16000-3c93-11eb-98dd-71e6ab619875.png)

**Comment by lynxlynxlynx** [comment] 2020-12-12 15:14
What an absurd searchmap! It looks like a duplicate of #1015 . I guess they did the minimum for it to be possible to access the cupboards, but yuck!

Do you have any saves from the original around there?

**Comment by FrElvire** [comment] 2020-12-12 15:20
No and don't have any original save (never played original in fact ;), this is my first run)

**Closed** 2020-12-12 22:16 UTC
Labels: bug, system: pathfinding
