### ISSUE TITLE
 Icewind Dale Complete crashing upon entering overworld map when using GemRB

### ISSUE THREAD

**Issue by HJ000001** [gemrb/gemrb#2104] opened 2024-07-18 06:30 UTC
#### Bug description
Hello devs,

I'm using the GoG version of Icewind Dale Complete with the latest version of GemRB.

The tavern loads fine after starting a new game, but as soon as I go outside it crashes. If I try to start the expansion directly it crashes right after character creation. Since I can go to the tavern cellar I am pretty certain that it is the game trying to load the overworld map which makes it crash.

Neither happens when I don't use GemRB, so I am certain that GemRB is the issues. I've tried changing several of the settings in the .cfg file, but it hasn't helped. I also couldn't see anything helpful in the log, although I don't know what exactly to look for either. 

#### Steps to reproduce
1. Select the Icewind Dale base game.
2. Create a character and start the game.
3. Leave the tavern.

OR 

1. Select the Icewind Dale HoW expansion.
2. Create a character and start the game.

#### Expected behavior
The overworld map should load.

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [X] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)

I don't know. I didn't change anything, so whatever is the default in GemRB 0.9.3 and a freshly installed Icewind Dale Complete Edition.

- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Here is the GemRB.log:**
http://paste.debian.net/1323609/

**Comment by lynxlynxlynx** [comment] 2024-07-18 06:42
This is on windows? Nothing sticks out from the log.

**Comment by HJ000001** [comment] 2024-07-18 07:08
Yes, this is on Windows 11 Pro.

It appears to me that the mere fact GemRB is used causes the crash. I've disabled every single line in the .cfg using # signs and it still happened.

**Comment by HJ000001** [comment] 2024-07-18 07:09
Yes, this is on Windows 11 Pro.

It happens even if every single line in the .cfg file is disabled using #, so it seems that the mere fact GemRB is used causes the crash.

**Comment by lynxlynxlynx** [comment] 2024-07-18 12:04
If you're using any sort of scaling, you can change the ScaleQuality config setting back from best to nearest, which will do less interpolation.

**Comment by MarcelHB** [comment] 2024-07-18 16:16
Hm, I can reproduce this using the official binaries. Compiling v0.9.3 on my own looks good.

**Comment by lynxlynxlynx** [comment] 2024-07-18 17:08
Just great. Can you make a release build and pack it up? If that works, we could just swap the binary on SF.

**Comment by MarcelHB** [comment] 2024-07-18 17:13
My default build is by GCC and that again relies on my MSYS2 env so I don't recommend doing this. I have to get a fresh MSVC for fixing this, whatever it is.

**Comment by lynxlynxlynx** [comment] 2024-07-18 19:24
@HJ000001 here are some build instructions in case you'd like to build the engine yourself: http://gemrb.org/MSYS2-build.html

**Comment by MarcelHB** [comment] 2024-07-18 23:29
Building this on MSVC here does not cause the error, but I found something half-way in CG that fails instead. Debugging with VS CMake-support isn't fun (like not updating code, or not offering cmd line options ...) and CMake solutions produce debug code that doesn't load with some of the vendored DLLs of vcpkg.

Some API tracers also don't give too much insights but I currently assume that we do something around https://github.com/gemrb/gemrb/blob/027f275f196278e1055734054e895f4e83d91a9a/gemrb/plugins/AREImporter/AREImporter.cpp#L1559-L156

that doesn't go through: I spot the attempt to look for `var.var` files, and then some more I/O calls before crashing.

**Comment by lynxlynxlynx** [comment] 2024-07-19 05:20
Interesting, with the save I'm using it crashes during "Loading actors" already.

**Comment by MarcelHB** [comment] 2024-07-19 13:33
I see that line as the last step, too, but also the log output does not look being flushed in time.

**Comment by MarcelHB** [comment] 2024-07-20 13:52
Well, appears to be a reincarnation of https://github.com/gemrb/gemrb/issues/1790

**Comment by lynxlynxlynx** [comment] 2024-07-20 14:02
You're right, the flags aren't even being tested for. Right after this there should be a bunch of them:
https://ci.appveyor.com/project/lynxlynxlynx/gemrb/builds/50250375#L398

**Comment by MarcelHB** [comment] 2024-07-20 14:20
The flags look good, no idea what AppVeyor should print here.

It's that we should apparently drop this flag on MSVC (that fixes it for me) since there is no better control over correctness reqs, unlike for GCC/Clang:
```diff
diff --git a/cmake/Helpers.cmake b/cmake/Helpers.cmake
index 6084862b6..d551b4956 100644
--- a/cmake/Helpers.cmake
+++ b/cmake/Helpers.cmake
@@ -119,10 +119,6 @@ FUNCTION(CONFIGURE_COMPILER)
 		ENDIF ()
 	ENDIF ()
 
-	IF(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
-		STRING(APPEND CMAKE_CXX_FLAGS " /fp:fast") 
-	ENDIF()
-
 	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" PARENT_SCOPE)
 	SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS}" PARENT_SCOPE)
 	SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS}" PARENT_SCOPE)
```

**Comment by lynxlynxlynx** [comment] 2024-07-20 14:26
Too bad, but still better than a crash. Perhaps we could use /fp:contract on MSVC 22, but I don't know if that would have any noticeable effect or if it would be problematic.

**Comment by lynxlynxlynx** [comment] 2024-07-21 12:53
Ok, just committed that and can confirm it fixes the problem. I've defaulted this build to the latest for windows and also changed the link on the website. Thanks again!

**Closed by lynxlynxlynx** 2024-07-21 12:53 UTC
Labels: bug, game: iwd1, portability
