### ISSUE TITLE
[bug] PST area animation clipping by wall groups

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#167] opened 2019-08-19 18:25 UTC
See #163 for previous discussion. Neither the animation in question nor the wallgroup has any cover bits set. Should PST wallgroups cover by default?

AR0508 example:
![ar0508_103_set](https://user-images.githubusercontent.com/238558/63229656-28666380-c203-11e9-8949-d9cb5b7eeb62.jpg)

_Originally posted by @MarcelHB in https://github.com/gemrb/gemrb/issues/163#issuecomment-522350499_

**Comment by lynxlynxlynx** [comment] 2019-08-19 18:30
It is relatively simple to write an https://github.com/gemrb/iesh script to check all PST areas and see how many area animations and wall polygons overlap. This would make answering the question about WF_COVERANIMS default value almost trivial, as the impact of the change could be exhaustively checked.

**Comment by lynxlynxlynx** [comment] 2020-05-12 16:07
Added some notes on the WED format from bg2 (91b4964ffb) — perhaps it will be useful for pst as well.

**Comment by anewusername** [comment] 2020-10-06 07:07
I took a look at this -- not sure if I did it right, but it looks like roughly ~500 individual overlaps across 89 area files.
I just took the 0th frame of each BAM, formed a rectangle based on (animation's center + frame's xy) and frame's dimensions, and then checked for intersection with wall polygons.

In any case, it doesn't seem like forcing (or inverting) WF_COVERANIMS would fix this; I get the below effect in either case:
![4BciWQ](https://user-images.githubusercontent.com/12633865/95168790-5b6e0c80-07a1-11eb-980c-ee8e2c0a9b70.png)
(on subviews, I don't see any effect from WF_COVERANIMS)

**Comment by lynxlynxlynx** [comment] 2020-10-06 07:25
Thanks for investigating! Can you list some of the other combinations, just so we have more test cases?

And huh, that's an interesting result. Looks like the two bottom animations get misplaced (handlebar gap and bottom).

Just for reference, the wall polygons:
![image](https://user-images.githubusercontent.com/121515/95170122-3a62e700-07b4-11eb-916f-63cce8e65ec7.png)

**Comment by bradallred** [comment] 2020-10-06 14:46
> (on subviews, I don't see any effect from WF_COVERANIMS)

You need to be using SDL1 or SDL2 + GL, plain SDL 2 can't blend using r/g/b channels.

**Comment by anewusername** [comment] 2020-10-07 06:22
Looks (close to) correct with SDL2+GL and forced WF_COVERANIMS:
![image](https://user-images.githubusercontent.com/12633865/95293589-3cd04a00-0863-11eb-997a-877d8cfcaa0c.png)

I went hunting for the other overlaps with WF_COVERANIMS forced and didn't see anything suspicious at the ones I could get to easily:
- Sensory stones under the brothel
- Molten metal in the foundry
- Mortuary torches
- Bottom edge of floor in Pharod's court (screenshots, seems fine to me?)
![AR0110](https://user-images.githubusercontent.com/12633865/95294746-58d4eb00-0865-11eb-9151-f13cfb0bd821.png)
![AR0110_poly](https://user-images.githubusercontent.com/12633865/95294496-e95efb80-0864-11eb-8e19-18435c3e1321.png)

[The full list](https://pastebin.com/UxzwKXUP) is decently long; I'll try to visit more of them. I've been using chilvence's saves from other issues to get around -- is there a comprehensive set of saves somewhere, or some way to quickly move between areas?

**Comment by MarcelHB** [comment] 2020-10-07 06:25
Open the console (Ctrl + Space), and do `mta("AR1234")` to where you like to travel.

**Comment by anewusername** [comment] 2020-10-07 07:25
Thanks! I bounced around a bunch and found the following:
- Northmost stone in the brothel basement is bad by default
![AR0606_disabled](https://user-images.githubusercontent.com/12633865/95299657-976ea380-086d-11eb-867d-c99594bc4bc7.png)
and gets fixed with WF_COVERANIMS toggled or forced:
![AR0606_enabled](https://user-images.githubusercontent.com/12633865/95299765-c08f3400-086d-11eb-9bb6-34ec5fcda496.png)

-AR0608 breaks when I force or toggle WF_COVERANIMS
![AR0608_disabled](https://user-images.githubusercontent.com/12633865/95299844-e0bef300-086d-11eb-9c0f-086642afb872.png)
becomes
![AR0608_enabled](https://user-images.githubusercontent.com/12633865/95299861-e87e9780-086d-11eb-86e3-2d5a57d276b6.png)
and this one no longer flashes:
![AR0608_toggled](https://user-images.githubusercontent.com/12633865/95299917-f8967700-086d-11eb-9a31-5eb68ddf52b1.png)

Most areas looked fine either way. In a few I couldn't find any animations at all; perhaps they're disabled somehow or need to be triggered? I'll keep looking.

**Comment by lynxlynxlynx** [comment] 2020-10-07 07:37
For the last image: is that (no flashing) good or bad?

**Comment by anewusername** [comment] 2020-10-07 19:25
I think it's supposed to flash (so get broken with WF_COVERANIMS).

**Comment by lynxlynxlynx** [comment] 2020-10-07 21:53
> Looks (close to) correct with SDL2+GL and forced WF_COVERANIMS:

The extra bad pixels might just be mistreated transparency, since this is near pure green and that's the palettes transparency color ... but upon a closer look, this does not seem to be the case in the data, the pixels are darker.

I'm out of ideas again. :/

**Comment by bradallred** [comment] 2020-10-08 15:57
That could just be a bad result of the dithering. probably the `BLIT_STENCIL_DITHER` shouldn't be applied to area animations.

**Comment by chilvence** [comment] 2020-10-08 17:45
@anewusername I keep meaning to do something about it, but I do have a whole bunch of saves staged from the original game that I need to shove somewhere. I made them roughly before / after any major event or new area. Shall I just make a github repo?

Regarding the last painting you mentioned, I tested it in the original game and I don't see any flashing... I think it's supposed to be a ripple animation?

**Comment by anewusername** [comment] 2020-10-09 01:46
> Shall I just make a github repo?
Sure, works for me. Might be worth linking it in the wiki on this repo, since that was the first place I thought to check.

> I think it's supposed to be a ripple animation?
I should have said it ripples... couldn't think of the right word :). 

I tried forcing `BLIT_STENCIL_DITHER` on or off but didn't see any difference.

**Comment by bradallred** [comment] 2020-10-09 17:38
> I tried forcing BLIT_STENCIL_DITHER on or off but didn't see any difference.

yeah, that makes sense since dithering should only occur with 50% alpha anyway.

the rough edges on those polygons is surely just lack of anti aliasing. I'm not sure the best way to address that.

**Comment by lynxlynxlynx** [comment] 2020-10-10 05:31
Saves: let's put them on sourceforge, they're just binary blobs.
Here's edheldil's: http://eowyn.cz/gemrb/

**Comment by chilvence** [comment] 2020-10-10 11:41
Well, if you'd like to link them somewhere here's mine:
https://drive.google.com/drive/folders/1zkaAqLcLEEHNPHwfqzHUgNZ-8r-aV0i5?usp=sharing

They're actually quite spaced out progression wise, since I only made minute by minute saves with my GemRB game, but they could be useful

Anyway, back to the original discussion :)

**Comment by anewusername** [comment] 2020-10-11 23:09
Thanks for the saves!

No luck with `SDL_HINT_RENDER_SCALE_QUALITY` unfortunately :( 

The issues with AR0608 inspired me to dig around in the animation flags a bit; [here's](https://pastebin.com/nTAs1fXV) my list of "unusual" flag values (inverted when that makes the list shorter) along with what area they appear in. (relevant to #163 too)

Main results:
- The combination of forcing `WF_COVERANIMS` and using 0x0008 as `A_ANI_NO_WALL` fixes both AR0608 and keeps AR0508 looking like the "good" (but jagged) version above. AR0606 (brothel basement) doesn't get the right result, but that might have been broken in the original? I'll see if I can find a windows machine and check it out.
- I'm pretty sure that 0x0100 is our `A_ANI_BLEND`, using it instead of forcing it on improves a lot of stuff (all of AR0608; print shop gears; AR0606 stones).

Other notes
- 0x0008 and 0x0010 are usually either both enabled or disabled. One of the few cases where they differ is the crystal (but *not* the fog) in AR1202, which doesn't have 0x0010. I wanted to assign `A_ANI_BACKGROUND` to 0x0010 so that actors wouldn't cover the chain and crystals in AR0608, but looking at the other animations, maybe it would need to be contingent on both having both bits set. In any case, I don't see any difference when forcing `A_ANI_BACKGROUND` on or off on any animation (?).

**Comment by anewusername** [comment] 2020-10-12 02:01
> the rough edges on those polygons is surely just lack of anti aliasing. I'm not sure the best way to address that

This seems right -- something either in how `poly->rasterData` is generated, or how `SDL_RenderDrawLine` handles the endpoints. If I force it to draw only outlines (force `fill=false` in `SDL20VideoDriver::DrawPolygonImp`) I get something quite reasonable:
![nofill](https://user-images.githubusercontent.com/12633865/95697058-0ca2f580-0c2d-11eb-830b-bc9b5c7ea299.png)

and in the debug coloring mode:
![fill](https://user-images.githubusercontent.com/12633865/95697354-fea1a480-0c2d-11eb-8a0d-88a84d2c9feb.png)
vs
![image](https://user-images.githubusercontent.com/12633865/95697565-b0d96c00-0c2e-11eb-8c47-5c771f18a8b9.png)

**Comment by bradallred** [comment] 2020-10-12 04:21
I'd have to see the changes to even guess at what you did, but if you want to antialias it I imagine just changing the end points of each line to 50% transparent would yield results.

**Comment by anewusername** [comment] 2020-10-12 04:57
For drawing the outline only:
```
diff --git a/gemrb/plugins/SDLVideo/SDL20Video.cpp b/gemrb/plugins/SDLVideo/SDL20Video.cpp
index bcdc2ce42..7214a10d4 100644
--- a/gemrb/plugins/SDLVideo/SDL20Video.cpp
+++ b/gemrb/plugins/SDLVideo/SDL20Video.cpp
@@ -479,6 +479,7 @@ void SDL20VideoDriver::DrawRectImp(const Region& rgn, const Color& color, bool f
 
 void SDL20VideoDriver::DrawPolygonImp(const Gem_Polygon* poly, const Point& origin, const Color& color, bool fill, uint32_t flags)
 {
+    fill=false;
        if (fill) {
                UpdateRenderTarget(&color, flags);
```

For the L-shapes:
```
diff --git a/gemrb/core/Polygon.cpp b/gemrb/core/Polygon.cpp
index 194163579..7b6405412 100644
--- a/gemrb/core/Polygon.cpp
+++ b/gemrb/core/Polygon.cpp
@@ -89,6 +89,7 @@ void Gem_Polygon::Rasterize()
                        if (!merged) {
                                rasterData[y].push_back(std::make_pair(Point(lt, y), Point(rt, y)));
                        }
+            break;
                }
        }
```

**Comment by bradallred** [comment] 2020-10-12 05:47
I didn't realize you were doing both `fill = false` and the break. that result is probably expected because now you are hitting `SDL_RenderDrawLines` instead of `SDL_RenderDrawLine` now. Why do you bother with forcing the fill to be false anyway? you are making the polygons into a single row of data so it's not useful. remove the `fill = false` and see if the result is what you expect then.

**Comment by anewusername** [comment] 2020-10-12 06:52
Sorry, I should have clarified; the two changes were disjoint (I only applied one at a time, wasn't sure which you were asking about).

A few of the calls sometimes do still have two segments, but filtering them out completely ( `if (lineSegments.size() > 1) continue;`  at the top of the outer loop) still draws the L-shapes. Same thing if I add a `break;` right after the `SDL_RenderDrawLine` call. No effect from the change from `rt` either.

====

I dug around the animation flags a bit more; I'm starting to suspect the draw order for AR0608 (and maybe others) might have been hardcoded. The flags and heights are the same for all the animations, but I confirmed that they draw on/under actors correctly in the original.

**Comment by bradallred** [comment] 2020-10-12 15:24
I dont know what version of SDL you have, but maybe try building from source

**Comment by bradallred** [comment] 2020-10-26 14:59
I wonder if the "L" shape has anything to do with [this bug](https://hg.libsdl.org/SDL/rev/0a38c9fd363d) just fixed in SDL

**Comment by anewusername** [comment] 2020-10-28 08:42
I finally got some time to try building SDL from latest source, and looks like it does fix the issue:
![reasonable](https://user-images.githubusercontent.com/12633865/97411931-cae6a000-18f8-11eb-8706-6987258bbf01.png)

I think I had two SDL versions installed previously and I'm not 100% sure if 2.0.12 was the one being used -- it's pretty likely though.

In any case, I'll take one more shot at figuring out the draw order situation (maybe stored in some other file altogether?) and then throw together a PR for the flags.

**Closed** 2020-11-16 07:27 UTC
Labels: game: pst, research needed, system: animations
