### ISSUE TITLE
[subviews] PST has wrong scrollbar in the identification service panel

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1219] opened 2021-04-04 14:58 UTC
#### Bug description
When you go identification-as-a-service at some mercheant, then to the right a description of the identified item appears. Naturally, this often has a lot of text. As you see below to the right, there are two sockets that are supposed to be mount points for a scrollbar, but it appears to the right. To the left, for the inventory scrollbar, this looks as exepected. master is good.

#### Screenshots
![pst_identify](https://user-images.githubusercontent.com/238558/113512860-f71ce180-9566-11eb-8d83-8b6f12f9178d.jpg)

**Comment by lynxlynxlynx** [comment] 2021-04-04 15:02
So this two things: a dupe of the wrong image issue and the mentioned pst exception of having some scrollbars on the left.

**Comment by lynxlynxlynx** [comment] 2021-04-05 13:57
Actually it's the correct scrollbar, but it is too high as well as being on the right

**Comment by bradallred** [comment] 2021-04-05 14:45
the solution is still the same for all these issues. We have to add a `SetScrollbar` method and move `MergeTextAreaAndScrollbar` to `ScrollView`. then it should be a simple matter of reparenting the scrollbar from the window to the `ScrollView`

**Comment by bradallred** [comment] 2021-04-05 15:38
there, now all that should remain to be done is to handle left handed scrollbars appropriately

**Comment by bradallred** [comment] 2021-04-09 17:51
I'm closing this. open a new issue if there are regressions. I didn't see any myself in PST.

**Closed by bradallred** 2021-04-09 17:51 UTC
Labels: game: pst, subviews, system: GUI
