### ISSUE TITLE
BG2 Inside the planar sphere golem don't do nothing 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1270] opened 2021-06-05 17:45 UTC
#### Bug description
After creating the golem in the planar sphere three different things happen:

- Golem start walking around in cut scene mode.
- Golem attack the party in cut scene mode
- Golem go to kill the intruders (Normal flow)

I have find this is wierd:

[GameScript]: Displaying string on: none
[FindPath/DEBUG]: s = (455, 1223), d = (390, 1320), caller = Arkon, dist = 0, size = 2
[GameScript]: Displaying string on: golemcontrolpanel
[ResourceManager]: Found 'cut22a.bcs' in 'chitin.key'.
**[GameScript/DEBUG]: CutSceneID was called by none!**
[ResourceManager]: Found 'CGUI1070.chu' in 'Override'.
[ResourceManager]: Found 'obsgol01.cre' in 'Override'.
[ResourceManager]: Found 'obsgolem.bcs' in 'chitin.key'.
[ResourceManager]: Found 'obsgol.bcs' in 'chitin.key'.
[ResourceManager]: Found 'cut22b.bcs' in 'chitin.key'.
[FindPath/DEBUG]: s = (434, 1224), d = (490, 1308), caller = Guardian Golem, dist = 0, size = 2
[ResourceManager]: Searching for 'WAL_MTc'...
[ResourceManager]: Found 'WAL_MTc.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'WAL_MT'...
[ResourceManager]: Found 'WAL_MT.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'WAL_MTb'...
[ResourceManager]: Found 'WAL_MTb.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'WAL_MTa'...
[ResourceManager]: Found 'WAL_MTa.wav' in 'chitin.key'.
[FindPath/DEBUG]: s = (416, 1420), d = (0, 0), caller = Guardian Golem, dist = 0, size = 2
[ResourceManager]: Found 'GUIOPT.chu' in 'chitin.key'.
[ResourceManager]: Searching for 'guierr2'...
[ResourceManager]: Found 'guierr2.mos' in 'Override'.
[ResourceManager]: Searching for 'gam_03'...
[ResourceManager]: Found 'gam_03.wav' in 'chitin.key'.
[Info]: Press ctrl-c (or close the window) again to quit GemRB.

GemRB version: v0.8.8

#### Steps to reproduce
1. Go to 'planar sphere'
2. Click on 'build golem'
3. See error

#### Expected behavior
Golem go to kill intruders

#### Screenshots

https://user-images.githubusercontent.com/1820598/120900700-a8460380-c60c-11eb-8588-0ac4657cbe50.mp4

[000000001-Quick-Save.tar.gz](https://github.com/gemrb/gemrb/files/6602972/000000001-Quick-Save.tar.gz)

**Comment by lynxlynxlynx** [comment] 2021-06-06 11:35
I tried your save 5 times and the golem always did as expected. Did you do anything specific to trigger the bug in the video?

**Comment by rsantellan** [comment] 2021-06-06 12:37
I click on the middle with the party around me and solo and it happens. I can't do nothing when it starts, I try doing CTRL + M to see if it works

**Comment by rsantellan** [comment] 2021-06-06 13:00
This time he attack me:

[FindPath/DEBUG]: s = (481, 1031), d = (394, 1316), caller = Arkon, dist = 0, size = 2
[ResourceManager]: Searching for 'ARM_03'...
[ResourceManager]: Found 'ARM_03.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'am0411d1'...
[ResourceManager]: Found 'am0411d1.wav' in 'chitin.key'.
[GameScript]: Displaying string on: golemcontrolpanel
[GameScript]: Displaying string on: aerie
[ResourceManager]: Searching for 'aerie18'...
[ResourceManager]: Found 'aerie18.wav' in 'chitin.key'.
[ResourceManager]: Found 'cut22a.bcs' in 'chitin.key'.
[GameScript/DEBUG]: CutSceneID was called by none!
[ResourceManager]: Found 'CGUI1070.chu' in 'Override'.
[ResourceManager]: Found 'obsgol01.cre' in 'Override'.
[ResourceManager]: Found 'obsgolem.bcs' in 'chitin.key'.
[ResourceManager]: Found 'obsgol.bcs' in 'chitin.key'.
[ResourceManager]: Found 'cut22b.bcs' in 'chitin.key'.
[ResourceManager]: Found 'mglcg12.bam' in 'chitin.key'.
[ResourceManager]: Found 'mglc.2da' in 'chitin.key'.
[2DAImporter/WARNING]: Bad signature (mglc.2da)! Complaining, but not ignoring...
[Actor]: Getting sound 2da mglc entry: Battle_Cry
[ResourceManager]: Searching for 'clayg02'...
[ResourceManager]: Found 'clayg02.wav' in 'chitin.key'.
[FindPath/DEBUG]: s = (434, 1224), d = (385, 1319), caller = Guardian Golem, dist = 65, size = 2
[ResourceManager]: Searching for 'WAL_MT'...
[ResourceManager]: Found 'WAL_MT.wav' in 'chitin.key'.
[FindPath/DEBUG]: s = (434, 1236), d = (385, 1319), caller = Guardian Golem, dist = 65, size = 2
[FindPath/DEBUG]: s = (434, 1248), d = (385, 1319), caller = Guardian Golem, dist = 65, size = 2
[InitRound]: Name: Guardian Golem | Attacks: 1 | Start: 3363533
[Actor/DEBUG]: Performattack for Guardian Golem, target is: Arkon
[ResourceManager]: Found 'itemsnd.2da' in 'GemRB Unhardcoded data'.
[ResourceManager]: Searching for 'gam_21a'...
[ResourceManager]: Found 'gam_21a.wav' in 'chitin.key'.
[Attack/COMBAT]: (Main) Left: 0 | Next: 3363623 [Missed]
[ResourceManager]: Searching for 'WAL_MTb'...
[ResourceManager]: Found 'WAL_MTb.wav' in 'chitin.key'.

**[InfoPoint/DEBUG]: Debugdump of InfoPoint Region golemcontrolpanel:**
**Region Global ID: 10030**
**Position: 276.1241**
**TalkPos: 0.0**
**UsePoint: 0.0  (on: No)**
**InfoString: The golem awakes and is transported out of the machine.**
** Script: golem, Key: , Dialog:  **
**Deactivated: Yes**
**Active: Yes**

[InitRound]: Name: Guardian Golem | Attacks: 1 | Start: 3363634
[Actor/DEBUG]: Performattack for Guardian Golem, target is: Arkon
[Attack/COMBAT]: (Main) Left: 0 | Next: 3363724 [Missed]
[ResourceManager]: Found 'mglcg21.bam' in 'chitin.key'.
[ResourceManager]: Found 'mglcg1.bam' in 'chitin.key'.
[InitRound]: Name: Guardian Golem | Attacks: 1 | Start: 3363735
[Actor/DEBUG]: Performattack for Guardian Golem, target is: Arkon
[Attack/COMBAT]: (Main) Left: 0 | Next: 3363825 [Missed]
[ResourceManager]: Found 'mglcg22.bam' in 'chitin.key'.
[InitRound]: Name: Guardian Golem | Attacks: 1 | Start: 3363836
[Actor/DEBUG]: Performattack for Guardian Golem, target is: Arkon
[Attack/COMBAT]: (Main) Left: 0 | Next: 3363926 [Missed]
[InitRound]: Name: Guardian Golem | Attacks: 1 | Start: 3363937
[Actor/DEBUG]: Performattack for Guardian Golem, target is: Arkon
[Attack/COMBAT]: (Main) Left: 0 | Next: 3364027 [Hit]
[ResourceManager]: Found 'INVTRAV.pro' in 'shared GemRB Unhardcoded data'.
[ResourceManager]: Found 'mglcg2.bam' in 'chitin.key'.
[ModifyDamage/COMBAT]: Resisted 0 of 32 at 0% resistance to 0
[Actor/COMBAT]: 32 unknown damage taken.

Tell me if I can send you more info.

**Comment by lynxlynxlynx** [comment] 2021-06-06 13:39
The golem has pretty simple scripts. The only way he would attack you is if he considered you an enemy. I've tried five more times and had the same result. I don't know what else to ask for, I simply cannot reproduce it.

**Comment by lynxlynxlynx** [comment] 2021-06-18 17:02
Closing. Do reopen if you find a way to make it break again (though no need to expend energy for that).

**Closed by lynxlynxlynx** 2021-06-18 17:02 UTC
Labels: bug, game: bg2, system: scripting
