### ISSUE TITLE
 [iwd1] Cone of cold animation and effect always oriented to bottom

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1341] opened 2021-07-04 17:37 UTC
#### Bug description
Cone of cold animation and effect always oriented to bottom, here launched with 'Owayn's lullabye'

[Unknown]: Projectile: 0
[Unknown]: Use item: shawm
[Unknown]: Extended header: 0
[Unknown]: Attacktype: 3
[Unknown]: Range: 25
[Unknown]: Target: 4
[Unknown]: Projectile: 0

SPWI504 using COCOLD.pro

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment] 2021-07-04 18:28
Does it work with the spell?
I think iwd has another coc opcode.
When opening issues please remove the instructions *for opening*.

**Comment by FrElvire** [comment] 2021-07-09 04:55
For the spell I don't know. Have you some easy way to test it ?

**Comment by lynxlynxlynx** [comment] 2021-07-09 07:21
Use a scroll?

**Comment by FrElvire** [comment] 2021-07-09 14:37
yes but I don't know where to find one.. I will try to find one in more shop.

If that can help, kontik use this spell and same effect (directed to bottom even if I'm in opposite direction)

![image](https://user-images.githubusercontent.com/55502325/125094679-c0111b80-e0d3-11eb-9e2c-f70ec74b3201.png)

Related log : 

```
[ResourceManager/ERROR]: Couldn't find 'wqMDDca.bam'.
[ResourceManager/ERROR]: Couldn't find 'wqMDDca.bam'.
[ResourceManager]: Found 'SPWI209.spl' in 'Override'.
[GameScript]: Displaying string on: berserk
[ResourceManager]: Searching for 'cas_m05'...
[ResourceManager]: Found 'cas_m05.wav' in 'chitin.key'.
[ResourceManager]: Found 'ENCHAT.pro' in 'GemRB Unhardcoded data'.
[ResourceManager]: Found 'enchat.bam' in 'chitin.key'.
[ResourceManager]: Searching for 'tra_02'...
[ResourceManager]: Found 'tra_02.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'eff_m05'...
[ResourceManager]: Found 'eff_m05.wav' in 'chitin.key'.
[ResourceManager]: Found 'ENCHAH.pro' in 'GemRB Unhardcoded data'.
[ResourceManager]: Found 'enchah.bam' in 'chitin.key'.
[ResourceManager]: Found 'SPWI119.spl' in 'chitin.key'.
[ResourceManager]: Found 'NECROT.pro' in 'GemRB Unhardcoded data'.
[ResourceManager]: Found 'necrot.bam' in 'chitin.key'.
[ModifyDamage/COMBAT]: Resisted 0 of 3 at 0% resistance to 64
[Actor/COMBAT]: 3 magic damage taken.

[ResourceManager]: Searching for 'H_RK_PT2'...
[ResourceManager]: Found 'H_RK_PT2.wav' in 'chitin.key'.
[Actor/COMBAT]: Damage animation type: 16
[ResourceManager]: Searching for 'eff_m07'...
[ResourceManager]: Found 'eff_m07.wav' in 'chitin.key'.
[ResourceManager]: Found 'NECROH.pro' in 'GemRB Unhardcoded data'.
[ResourceManager]: Found 'cemf4g14.bam' in 'chitin.key'.
[ResourceManager]: Found 'necroh.bam' in 'chitin.key'.
[ResourceManager]: Found 'SPWI504.spl' in 'chitin.key'.
[ResourceManager]: Searching for 'CHA_fm11'...
[ResourceManager]: Found 'CHA_fm11.wav' in 'chitin.key'.
[ResourceManager]: Found 'invoccg.bam' in 'chitin.key'.
[GameScript]: Displaying string on: berserk
[ResourceManager]: Found 'COCOLD.pro' in 'GemRB Unhardcoded data'.
[ResourceManager]: Searching for 'tra_08'...
[ResourceManager]: Found 'tra_08.wav' in 'chitin.key'.
[ResourceManager]: Found 'cocoldt.bam' in 'Override'.

```

**Comment by FrElvire** [comment] 2021-07-13 05:13
With kontik use of this spell do you have enough information or not ?

**Comment by lynxlynxlynx** [comment] 2021-07-13 06:41
Yes, thanks.

**Comment by lynxlynxlynx** [comment] 2022-03-19 18:08
Was already fixed, didn't realize it was a duplicate of the remainder of #515.

**Closed by lynxlynxlynx** 2022-03-19 18:08 UTC
Labels: bug, game: iwd1, system: effects
