### ISSUE TITLE
 BG1: Music keeps on playing

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2008] opened 2024-02-22 11:53 UTC
#### Bug description
Whenever a new background music is playing it keeps on playing even when the "situation" is over.

#### Steps to reproduce
1. Start gemrb, start a new game, hear the main theme music at the character creation (still ok)
2. New game starts before the Candlekeep Inn, main theme music still plays
3. Go into Candlekeep Inn, hear the tavern music
4. Go outside Candlekeep Inn, tavern music still plays
5. Go to house in the north where Skunk is attacking you, hear battle music
6. Battle is over, go outside, battle music still plays

#### Expected behavior
Music stops playing when appropriate.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment] 2024-02-22 13:47
Basically a duplicate of #1854.

**Closed by lynxlynxlynx** 2024-02-22 13:47 UTC
Labels: bug
