### ISSUE TITLE
[BG2 at last] Hard to speak to NPC when spammed with messages

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#760] opened 2020-05-26 10:41 UTC
#### Bug description
In Saradush we are always spammed with messages so speaking to certains NPC is very hard even when minimizing feedback.

GemRB version: master/SDL2

#### Expected behavior
game paused like some other conversations (what is the criteria) ?

#### Video
[conversation.zip](https://github.com/gemrb/gemrb/files/4681570/conversation.zip)

**Comment by lynxlynxlynx** [comment] 2020-05-26 14:01
Ideally the dialog would just have its pause bits set. Instead this is now a duplicate of #405, just that printing below would probably cause the same issue.

**Comment by FrElvire** [comment] 2020-05-27 09:25
With subviews branch, the behavior is the same although with the support of the mouse wheel it's a little easier 👍

**Comment by FrElvire** [comment] 2020-05-27 09:49
if it can help (TOB save)

[000000011-conv spam.zip](https://github.com/gemrb/gemrb/files/4687931/000000011-conv.spam.zip)

**Comment by lynxlynxlynx** [comment] 2022-09-10 21:00
Check if you have Subtitles=1 in gem-baldur.ini; that's a big source of spam, since many guards are scripted to shout via DisplayStringHead. I'll make it skip printing for offscreen sources though. 

But testing this shows we have a regression in handling non-pausing dialogs. Actors do their scripted moves, the pendulum swings, birds fly, BUT the area animations are stopped, combat is stopped, so there's a fake sense of success wrt this bug.

**Closed** 2022-09-11 09:12 UTC
Labels: bug, system: core

**Comment by rsantellan** [comment] 2022-09-13 17:39
@lynxlynxlynx  It just happen to me:

![image](https://user-images.githubusercontent.com/1820598/189547698-2c61c6c1-aaa1-4666-9d0a-0e8b63751d1b.png)

They should not wait until conversation is finish to show ?

**Comment by lynxlynxlynx** [comment] 2022-09-15 18:35
Those are different, but yeah, makes sense to postpone.
