### ISSUE TITLE
[BG2] Anomen's Test not trigrered 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#688] opened 2020-04-17 07:50 UTC
#### Bug description
In Anomen's quest (BG2), Sir Ryan Trawl request Anomen to come to the Order's Headquarters in the Temple District.
Once in, there is nothing, Sir Ryan Trawl is here but if you speak to him all it says is : good day to you <name of the *leader*>
[000000058-begin 6 - out of underdark.zip](https://github.com/gemrb/gemrb/files/4491611/000000058-begin.6.-.out.of.underdark.zip)

GemRB version: master

#### Steps to reproduce
1. Use the save provided
2. go to Order's Headquarters in the Temple District
3. Sir Ryan Trawl request Anomen to come to the Order's Headquarters
3. deal with githyanki who want the silver blade
4 Enter in Order's Headquarters in the Temple District and...nothing

#### Expected behavior
Once you enter the Order's headquarters, Anomen takes over and goes to take his test, bringing only you with him.

#### Video
You can see in video instead of taking time to play it : https://sendeyo.com/show/e25234e545

#### Screenshots
![Anomen](https://user-images.githubusercontent.com/55502325/79545314-c2332880-8090-11ea-9dc6-8d00388a739d.jpeg)

**Comment by lynxlynxlynx** [comment] 2020-04-17 18:59
Playing with that whine is not supported, by design.

Just kidding. I immediately see a problem before this. Talking to Drizzt doesn't work if Keldorn wants to interject, since he has the wrong dialog set. As for Anomen, you hit an old bug fixed in the previous release, so it's another thing to file under "buggy save". You can work around it by killing Anomen. :) Resurrecting him will fix the problem. You can use ctrl-y and ctrl-r.

**Closed by lynxlynxlynx** 2020-04-17 18:59 UTC
Labels: bug, game: bg2, system: scripting

**Comment by FrElvire** [comment] 2020-04-18 07:37
Thank you, it worked perfectly :) , killed and resurrect them all but the leader to help prevent filling false report and loosing your time.
