### ISSUE TITLE
Rendering of many actor animation effects wrong

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1559] opened 2022-02-12 00:58 UTC
I found that 3a7284432b4c9584f9eb7866a96a986897c17a91 had a bad impact on rendering actors. See also #397, or the following screenshots

Before: alpha channel effects, CLOAKSC rotating colors on all parts
![Screenshot_2022-02-12_01-51-27](https://user-images.githubusercontent.com/238558/153689496-989ce09f-770e-4f7b-839b-583539ec0b13.png)
After:
![Screenshot_2022-02-12_01-53-02](https://user-images.githubusercontent.com/238558/153689543-2c37a210-9a5f-4348-aede-985f7758022d.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment] 2022-02-12 01:34
feels like this is probably more or less a dupe of the other issue we have regarding transparency

**Comment by lynxlynxlynx** [comment] 2022-02-12 08:49
Yeah, #1511 or #1514.

**Closed by lynxlynxlynx** 2022-02-12 08:49 UTC
Labels: bug
