### ISSUE TITLE
IWD2: Clicking into empty space in CG quits it 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1526] opened 2022-01-26 23:09 UTC
In IWD2 CharGen, whenever you click somewhere that is not a UI component such as a button, the game kicks you out back to the main menu. No Python errors around but quite frustrating to encounter.

![iwd2_cg](https://user-images.githubusercontent.com/238558/151262211-917a5d91-ec34-42a5-a3d2-691274b1a251.gif)

**Comment by bradallred** [comment] 2022-01-27 01:05
I doubt its kicking you anywhere, sounds like the click is passing though to the window below and focusing it. I don't know why a background click would pass though, I dont _think_ we do that on purpose ever (we do when its transparent, but thats not the case here).

Regardless of the possible clickthrough bug, the chargen should be made modal which would disallow focusing the main window.

**Comment by lynxlynxlynx** [comment] 2022-01-27 07:15
Something similar is also achievable through the keyboard and I didn't see it in other games. Where you would usually use enter to speedrun chargen, it now kicks you back. But not back to the previous step or to start the character over (what the buttons do), but actually one step farther back, to the pregen party selection.

**Comment by bradallred** [comment] 2022-01-28 20:30
Are you using a nonstandard resolution? It looks like `View::HitTest` probes the background image for transparency, but doesn't appear that we adjust the point to compensate for the background image being centered within the view.

**Comment by MarcelHB** [comment] 2022-01-28 20:32
It's just 1024x786.

**Comment by lynxlynxlynx** [comment] 2022-01-28 21:17
Mine was at the default 800x600.

**Comment by lynxlynxlynx** [comment] 2022-03-06 08:19
iwd2 uses two windows in several steps of cg, but this is reproducible already at the start, when there's only one (and it fills the screen). The previous one are full as well and not marked as modal. At the time of the click there's then only the start window and the cg one in the window list. Which I find odd, since the party choice and formation windows are from a third windowpack.

Anyway, View::HitTest fails since the window is set as IgnoreEvents (I guess for later, when there are two windows at once) and since there's no control to intercept it, Window::HitTest fails as well and the next window is tried.

**Closed** 2022-03-06 18:46 UTC
Labels: bug, game: iwd2, system: GUI
