### ISSUE TITLE
[bug] BG2: Party gets XP during first Candlekeep dream cutscene

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#206] opened 2019-09-06 11:22 UTC
**Description**
During the Candlekeep dreams in Chapter 2 the party gets XP for actors killed in the cutscenes (like Elminster, Gorion, Sarevok). Also, the PC has listed in the statistics under 'Most powerful enemy vanquished': 'Elminster'. That's not the case in the original IE.

**GemRB version**
0.85 and prior

**To Reproduce**
You could probably start a new game, change the chapter Global to 2 and rest a couple of times... check the in-game message window for the XP gain and take a look at your main character's statistics.

**Comment by lynxlynxlynx** [comment] 2019-09-06 14:04
Hmm, maybe we just need to exclude these two things for all cutscenes. Easy to do, just trying to think of any cutscenes where this was important — but can't. Or maybe it's dream areas that are excluded.

Can you check with a dummy cutscene in the original?

**Comment by caillean7** [comment] 2019-09-06 14:31
> dummy cutscene
Uh - you don't mean if I could write one? Or adding something to another, e. g. the very first one in Irenicus' dungeon at game start?

**Comment by lynxlynxlynx** [comment] 2019-09-06 15:32
Either would work, but that particular one is a bit extra, since you're locked up, so you'd have to teleport out first and then attack a spawned rat for example. If you don't get xp, then it's cutscenes, if you do, it's more likely to be dream areas, but not fully confirmed. 

You can also try just teleporting to one of the dreams from some early save and see if you get xp for attacking npcs (please make sure they have an xp value),

**Comment by caillean7** [comment] 2019-09-06 15:55
Again I strayed from the awesomeness that is GemRB and fired up EE. Moved to the first Candlekeep dream and killed Sarevok - no XP gain, see screenshot.
![screen](https://user-images.githubusercontent.com/54738589/64442078-7b7b5a00-d0cf-11e9-8f59-d787377d6f4a.jpg)

**Comment by caillean7** [comment] 2019-09-06 16:25
Okay, I tried spawning dream Elminster, which is ELMIND.cre, which has 26000 XP value. Killed him, no XP. Game is BG2:EE Linux.
![screen](https://user-images.githubusercontent.com/54738589/64444022-81733a00-d0d3-11e9-98be-09448b110198.jpg)

**Comment by caillean7** [comment] 2019-09-06 16:49
Killing a random creature (e.g. Goblin or Gnoll) that has nothing to do with the dreams in the dream area will get you xp. If you kill it yourself with a weapon. Things like ForceSpell in cutscenes shouldn't yield xp, however. And some cutscene scripts do add xp with AddXP2da for plot purposes, so preventing xp gain in cutscenes altogether wouldn't be a good idea. So could you just prevent the xp in the vanilla games' dream cutscenes? Perhaps how this should be handled could also be a question to ask modders over at G3?

**Comment by lynxlynxlynx** [comment] 2019-09-06 21:10
Hmm, so it is more complicated. These cutscenes, are you the slayer offing them in melee or is this scripted spellcasting that you mention? I wonder if there's a difference (please try the other dreams and look into the scripts for the killing actions).

Can you check what this special Elminster has set for his creature flags? These in the header: https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm

If that  doesn't yield anything useful, it may be time to scour the archives indeed.

**Comment by caillean7** [comment] 2019-09-07 01:59
I did attack them with weapons I gave the chars with the console. In case of dream Elminster, I can't hit him, since he has an AC of -9. He just dies after a while. Script name in NearInfinity says 'elmind', but there's no script elmind.bcs. He doesn't have any creature flags set, neither in the classic BG2 nor in EE.

This is how dream Elminster, Gorion and Khalid are killed in 'cut28d':

`ApplySpell("goriond",SURE_STONE_SHATTER)  // Gorion`
`ApplySpell("elmind",SURE_STONE_SHATTER)  // Elminster`
`ApplySpell("khalidd",SURE_STONE_SHATTER)  // Khalid`

So it's not Charname who does the killing, that's so weird about getting xp for this.

Will play through the other dreams with GemRB now, checking if and for what there's more xp for the party. I already checked the dream scripts: Creatures are killed with (Really)ForceSpell mostly or just Kill in the case of the peasants in Candlekeep Library. Then I'll go back to EE to see what happens if I attack creatures in those areas with weapons.

**Comment by caillean7** [comment] 2019-09-07 02:26
Findings: In the second ("Life ... is strength...") and third ("Stand. ...") dream there's no XP gain for the party, so this affects only the first dream at all:

![screen](https://user-images.githubusercontent.com/54738589/64468528-0424e500-d126-11e9-80ff-7299708c3881.jpg)

**Comment by caillean7** [comment] 2019-09-07 02:50
Another one since I can't sleep: I wondered if this is connected to the spell used here (SURE_STONE_SHATTER) and the way GemRB handles it, so I checked this, too. It is only used in the dream cutscenes and one other occasion: The Waukeen's Promenade Cutscene after leaving Irenicus' dungeon in chapter 1. An assassin with an xp value of 15 is killed here. I played through it, but no 15 xp for the party during this cutscene, so you can probably rule this out as well.

**Comment by lynxlynxlynx** [comment] 2019-09-07 09:31
SURE_STONE_SHATTER is spin888, which uses fx_death. There's no reason why we should give XP if nobody from the party is involved. I'll investigate, sounds like a simple fix. Thanks for the details.

**Comment by lynxlynxlynx** [comment] 2019-09-07 11:19
cut28d is ran by Player1, so we think he's the caster and everything else then makes sense. I don't see any other uses btw, only in these cut28* cutscenes.

**Comment by caillean7** [comment] 2019-09-07 11:57
You're right, that was the EE installation I checked on. In classic BG2 that spell is in fact only used in the dream cutscenes (honestly, I didn't think the versions would differ in this classic content, but there it is)

**Comment by lynxlynxlynx** [comment] 2019-09-07 12:54
This should be fixed now. Please reopen if that's not the case.

**Comment by caillean7** [comment] 2019-09-07 13:06
FIXED. Thank you!

**Comment by lynxlynxlynx** [comment] 2019-09-18 19:47
IS AddXP2da the only way cutscenes grant xp?

**Comment by caillean7** [comment] 2019-09-21 17:50
Normal method as in killing stuff? Like cutscene makes party attack and kill creature X - be it with spells or melee?

**Comment by lynxlynxlynx** [comment] 2019-09-21 19:14
Exactly, eg. ActionOverride(Attack(someone)).

**Comment by caillean7** [comment] 2019-09-22 12:15
I changed one the vanilla cutscenes in EE to let Player1 attack and kill two creatures with an XP value. As soon as the game went out of cutscene mode, the XP got added. 

So I guess the conclusion is that you get XP in a cutscene only through script actions, XP from killing anything is added after the cutscene is over.

**Comment by lynxlynxlynx** [comment] 2019-09-22 12:49
Huh. So does EE also grant the xp for the kills from the original description of this report?

**Comment by caillean7** [comment] 2019-09-22 12:58
No, it doesn't. The dream cutscene does ApplySpell on the creatures, there's nothing like ActionOverride(Player1), so it's not Player1 who does the killing. I think there's the difference.

**Comment by lynxlynxlynx** [comment] 2019-09-22 16:10
The cutscene is ran by Player1, so the code sees no difference. I could adapt the original fix, so it applies only in cutscenes, but it doesn't make perfect sense. Not that I expect as much from IE, but this is in a place that could easily break other stuff, so we need to be more careful. Will try something uglier, but narrower in scope.

**Comment by caillean7** [comment] 2019-09-22 16:22
Yes, because of the CutSceneID, so perhaps the IE kind of filters it, prevent xp if it comes from certain actions like the ApplySpell, or maybe Kill or whatever. Is something like that practical? Or disable xp gain in cutscenes altogether, except for the script added xp of course.

**Comment by lynxlynxlynx** [comment] 2019-09-22 17:07
Try now.

**Comment by caillean7** [comment] 2019-09-22 17:17
No more XP, that works. It still lists Elminster in "Most powerful enemy vanquished", though.

**Closed** 2019-09-23 07:13 UTC
Labels: bug, effects, research needed
