### ISSUE TITLE
[feature] door highlights are of different color

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#102] opened 2019-02-04 21:46 UTC
**Description**
We currently highlight doors with the same color as containers. TAB was used in some games for this highlight (we use ALT for everything).

The color was light purple (red in iwd2), not the container blue. We need to externalize these colors into a table and then use that in core. This has been done — the table is colors.2da and one can use gamedata->GetColor("color-row-name") to get a specific entry.

And PST is just annoying, but this can be ignored for now:

> Highlighting of containers, doors etc. in PS:T was done differently
> 
> - no edge line
> - instead of almost opaque polygon drawn over it, in PS:T the object changes hue from whitish to cyanish, as if the red channel was set to 0 or something like that. Possibly it's done by calculating pixel lightness in HLS space and then mapping it to cyan gradient or st. like that.

**Comment by bradallred** [comment] 2020-12-11 01:08
the PST portion of this is fixed by #618

**Comment by rsantellan** [comment] 2021-07-07 02:04
Hi @lynxlynxlynx I have a question about the color format.

![image](https://user-images.githubusercontent.com/1820598/124688667-8eb70680-dead-11eb-9e2d-e9d01e53b90e.png)

That is the color in the original, in html will be a **3abeb7**

In which format is on the table ? 
https://github.com/gemrb/gemrb/blob/6cdc73df9e9c7a35cfa87cb0891d8c9327e2d412/gemrb/unhardcoded/shared/colors.2da#L6 

Should I add to all the games or if I add it on the shared will be overridden on the game specifics ? 

I found where to change it: https://github.com/gemrb/gemrb/blob/6cdc73df9e9c7a35cfa87cb0891d8c9327e2d412/gemrb/core/Map.cpp#L1183
And do some testing using: **d->outlineColor = gamedata->GetColor("MAPTXTBG");**
And is working... Only missing is the color format.

**Comment by rsantellan** [comment] 2021-07-07 02:23
For answering some of my questions...
If I put it on the shared it will be **shared**
![image](https://user-images.githubusercontent.com/1820598/124690667-ec008700-deb0-11eb-9e9c-a27d3acb9dcb.png)
Now I'm only missing the color... it turn out red my test...
```
2DA V1.0
0xffffffff
				COLOR
TOOLTIP			0xffffffff
TOOLTIPBG		0x00000000
MAPICNBG		0xffffffff
MAPTXTBG		0x00000000
DOORTEST		0x3ABEB700
```

**Comment by lynxlynxlynx** [comment] 2021-07-07 06:58
By the looks of the value perhaps BGRA? Try setting only each pair and you'll quickly find out.

**Comment by bradallred** [comment] 2021-07-07 14:41
the colors in colors.2da are in RGBA format. We should probably add a comment to the file.

**Comment by lynxlynxlynx** [comment] 2021-07-07 17:12
Just one of the preset colors, so mistakes stand out. You'll have to share more of your code @rsantellan.

**Comment by rsantellan** [comment] 2021-07-08 12:55
@lynxlynxlynx I have this: https://github.com/rsantellan/gemrb/commit/f520fb3602a9686b5da99527169f28628b0a356e

**Comment by bradallred** [comment] 2021-07-08 13:17
as I mentioned above, you are editing the wrong colors.2da

you want [this one](https://github.com/gemrb/gemrb/blob/master/gemrb/unhardcoded/bg2/colors.2da)

**Comment by lynxlynxlynx** [comment] 2021-07-08 15:58
All of them, in the end.

**Comment by rsantellan** [comment] 2021-07-09 01:35
@bradallred changing that one make it.

![image](https://user-images.githubusercontent.com/1820598/125010226-82ad7f00-e03c-11eb-8cd8-a844856188c8.png)

I set it to Yellow to see the difference. Now I have to play with [RGBA](https://htmlcolors.com/rgba-color) and [HEX](https://coding.tools/rgba-to-hex) to find the correct color.

**Comment by rsantellan** [comment] 2021-07-12 13:18
I have found a color that I like, the problem is the hidden doors:

![image](https://user-images.githubusercontent.com/1820598/125293981-4c048c80-e2fa-11eb-9d28-8f0b96d86910.png)

The color of the hidden doors is **ColorMagenta {0xff, 0x00, 0xff, 0xff}** and I don't know how to change it to RGBA :(

**Comment by lynxlynxlynx** [comment] 2021-07-12 13:39
What do you mean? It's already in RGBA ... with the small caveat that we have alpha inverted.

**Comment by bradallred** [comment] 2021-07-12 13:41
> The color of the hidden doors is ColorMagenta {0xff, 0x00, 0xff, 0xff} and I don't know how to change it to RGBA :(

that _is_ RGBA format for magenta. All the predefined `Color`s are in RGBA.

**Comment by rsantellan** [comment] 2021-07-12 13:51
@bradallred I want to see them like this: RGBA(124, 17, 236,1) so I can see the color but don't know how to convert them yet.

**Comment by MarcelHB** [comment] 2021-07-12 13:56
Open a calculator application, put every decimal value in and switch to hexadecimal. Done.

**Comment by rsantellan** [comment] 2021-07-12 14:12
Thanks @MarcelHB 
So the hidden doors is: 
![image](https://user-images.githubusercontent.com/1820598/125301981-eae0b700-e301-11eb-81d9-55a2c38b76fa.png)
And the doors will be:
![image](https://user-images.githubusercontent.com/1820598/125302099-09df4900-e302-11eb-8d43-b3dd8705a51c.png)
Don't know what all think.

**Comment by lynxlynxlynx** [comment] 2021-07-12 14:29
For what gets into the repo, it should match the originals. So for bg2, that's the same color as secret doors.

Do note that this is highlighting is just different on TAB, mouse overing should still be the same blue for both containers and doors.

**Comment by bradallred** [comment] 2021-07-12 14:48
I'll bet whatever tool you are using has an option to display with hexadecimal values

**Comment by rsantellan** [comment] 2021-07-14 02:07
@lynxlynxlynx this is the original

https://user-images.githubusercontent.com/1820598/125549220-373c5f66-5077-48ea-8b44-3488f3132a0b.mp4
This is my last change.

https://user-images.githubusercontent.com/1820598/125549224-87fe9e24-3f1f-4000-8909-d7a93ffe1644.mp4

Now I have an issue that I can only test it on BG2... What I do with the rest of the colors.2da ?

**Comment by lynxlynxlynx** [comment] 2021-07-14 06:27
For pst you can add any color you want, just add a comment before that it's not used.
For iwd2:
![image](https://user-images.githubusercontent.com/121515/125573268-6b28ea70-5b06-4e2f-a245-f6aa143ae27d.png)
![image](https://user-images.githubusercontent.com/121515/125573207-c2f3a290-f57f-4e7b-a629-556af9552ba5.png)
bg1 had a slightly different hover highlight type, but nobody cares and the color is the same:
![image](https://user-images.githubusercontent.com/121515/125573652-732afce3-ba9c-4e72-b106-ce6781101e1b.png)

Most games didn't have highlighting on a hotkey, so we can use the same value as for bg2.

**Closed** 2021-08-09 06:35 UTC
Labels: feature, system: core, good first issue
