### ISSUE TITLE
 Spell memorization windows refresh issue

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1843] opened 2023-07-02 17:22 UTC
#### Bug description
The spell memorization scripts refresh the lists of memorized spells in either the wrong place or not often enough.

If you memorize/unmemorize a spell from either the priest or mage spellbooks the icon disappears and so does the frame. 

If you memorize more than one spell any previous newly memorized slot retains a black overlay that is removed on mouseover or screen change (see video 3 below)

#### Steps to reproduce
1. Go to a priest or mage character's spellbook
2. Click on a known spell to memorize it, or click on a memorized spell to remove it
3. The spell slot frame is missing until the window is refreshed by reopening it.

#### Expected behavior
The spell icons/frames for memorized spells should refresh automagically and be visible without having to mouseover or reopen the window.

#### Screenshots
This video shows the current behaviour.

[cinnamon-2023-07-02T132957-0230.webm](https://github.com/gemrb/gemrb/assets/137374871/389c0bb4-98e0-4633-ab8c-4a5060b932ea)

This video shows the behaviour with modification to the placement of the refresh function in the GUIMG and GUIPR scripts.

[cinnamon-2023-07-02T135316-0230.webm](https://github.com/gemrb/gemrb/assets/137374871/5d0349e5-27bc-44d5-9db5-e33d14f22b21)

This video is with script changes that refresh the list so it refreshes the icons and frames so they are visible, but newly memorized spells before the current slot have a black overlay (removed on mouseover) that I still trying to track down.

[cinnamon-2023-07-02T144655-0230.webm](https://github.com/gemrb/gemrb/assets/137374871/3c994215-377d-4478-8b9f-83aefac6283a)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by gregariousmonk** [comment] 2023-07-02 17:22
I'll submit a pull request once I've sorted how to refresh the view to remove the overlay.

**Comment by lynxlynxlynx** [comment] 2023-07-02 17:36
This is pretty much a duplicate of #1340.

**Comment by gregariousmonk** [comment] 2023-07-02 19:57
I've managed to get the GUI scripts to refresh the frame and icon for the spells, but the eliminating the residual black overlay from the animation remains elusive.

**Comment by lynxlynxlynx** [comment] 2023-07-02 21:43
The drawing artefacts are likely not fixable through the python glue. 
If those PRs are for us, you've opened them against the wrong repository. ;)

**Comment by gregariousmonk** [comment] 2023-07-02 21:59
Indeed they are and yes, they are. I'm still figuring out how this works, lol.

I'll figure it out and do them correctly. :)

**Comment by lynxlynxlynx** [comment] 2023-07-02 22:27
Thanks, I'vemerged that manually, so it's a single commit. And the black stuff can remain in the old issue.

**Closed by lynxlynxlynx** 2023-07-02 22:27 UTC
Labels: bug, system: GUI

**Comment by gregariousmonk** [comment] 2023-07-02 22:45
I've been trolling through the button/gui code trying to find a function that might kick it as the mouseover event seems to do, but I'm currently sitting by my firepit drinking vodka with lime juice.  

Not really fixing the problem, but I am learning a bunch. :)

**Comment by bradallred** [comment] 2023-07-03 15:27
If you look at the icons in #1340 it's pretty clear that the blend mode is wrong. it should be something like `ONE_MINUS_DST`.
