### ISSUE TITLE
Bad visual when adding/removing spell

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1340] opened 2021-07-04 10:50 UTC
#### Bug description
I'm almost sure this bug existed earlier and was corrected. when you add or remove a spell, there is some graphical bug (animated when game not paused)

#### Steps to reproduce
1. go to (mage) spell book
2. select a new spell

#### Expected behavior
Add a clear and concise description of what you expected to happen.

#### Screenshots
add
![spell_add](https://user-images.githubusercontent.com/55502325/124382135-31149580-dcc6-11eb-97f4-da792be51389.png)

remove
![spell_remove](https://user-images.githubusercontent.com/55502325/124382189-70db7d00-dcc6-11eb-9dac-b39eb83d3b10.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment] 2021-07-04 12:39
Looks like just the transparency is off for the effect bam.

**Comment by FrElvire** [comment] 2021-07-18 14:43
I fear his bug is always here.

**Comment by lynxlynxlynx** [comment] 2021-07-18 15:49
Yeah, can confirm. Also this various level of blackening of previously deleted slot from your other screenshot. Everything animates at the same time.
![image](https://user-images.githubusercontent.com/121515/126073646-9998dbe8-74f7-4b54-a50f-937f99454cd7.png)

**Comment by lynxlynxlynx** [comment] 2021-08-12 16:12
While in iwd2 the full animation doesn't finish, so a gui refresh is needed for the proper "icon" to appear.

**Comment by fizzet** [comment] 2022-01-16 16:38
I fixed some of the issues mentioned here, but there's still something funky going on with drawing the border for newly memorized spells.

**Comment by bradallred** [comment] 2022-01-17 20:43
I guess reopen if that didn't do the trick

**Comment by bradallred** [comment] 2023-07-03 15:42
This is _possibly_ two problems.

First is that the blend mode is incorrect; it should be something like `ONE_MINUS_DST`. In fact, if you look at 2be9403 you will see that I changed the BG2 `FlashResRef` due to probably the same issue. I should have checked the other games, because it seems like at least IWD does this too. I'm not sure what BAMs are available in all the games, but the fix would be either to change IWD to the alternate BAM like I did with BG2, or revert that BG2 change and just change the blend mode.

It's possible that fixing the blend mode makes everything look fine, but that wouldn't explain why things keep getting reapplied. Seem like there is a bug with either `Button::IsOpaque` or something else controlling when we clear the RenderTarget for redraw.

**Comment by bradallred** [comment] 2023-07-03 17:53
ah, so all the other games use FLASH.BAM for the icon requiring `ONE_MINUS_DST`, where with BG2 it is FLASHBR.BAM. It does look like `ONE_MINUS_DST` is being applied everywhere then, which should have resolved the funky artifacts in OP, but it looks like the source of increasing darkness is going to be something else, like an overlay.

**Comment by bradallred** [comment] 2023-07-03 18:26
ok, it looks like the bug is here:
https://github.com/gemrb/gemrb/blob/e16dad0787d4cfa48a1f7e5480d16e770cbaeb2b/gemrb/core/GUI/Button.cpp#L361-L368

we should also be checking that the animation is not complete.

**Comment by bradallred** [comment] 2023-07-03 20:17
hmmm, I'm not so sure since we should be clearing the animation when it ends:
https://github.com/gemrb/gemrb/blob/e16dad0787d4cfa48a1f7e5480d16e770cbaeb2b/gemrb/core/GUI/Button.cpp#L114-L119

the problem then would be that the animation doesn't have `PLAY_ONCE` set.

Can't really tell you tho, because _I cannot reproduce this issue_. Is this for a specific game only? I tried all that I have, but couldn't test with IWD, because there are guiscript errors when loading my saves.

I'm un-assigning this from myself since I cannot even reproduce this.

**Comment by lynxlynxlynx** [comment] 2023-07-03 20:32
I still easily get some of the black (testing iwd), but I doubt it's a per-button problem.
My steps:
- have at least 2 free slots available
- memorize spell (plays fine)
- memorize another (plays fine, but the previous slot gets black until hovered over)

**Comment by bradallred** [comment] 2023-07-03 22:15
> * memorize another (plays fine, but the previous slot gets black until hovered over (one or the other slot, but nothing else fixes it))

thank you! this is the critical step that is not mentioned in the issue post.

**Comment by bradallred** [comment] 2023-07-06 00:06
I've identified the cause, but I'm going to defer fixing it until after 0.9.2 as it is easy to introduce subtle regressions with drawing.

**Closed** 2023-07-17 19:11 UTC
Labels: bug, system: GUI
