### ISSUE TITLE
[PST] Regression in 0.8.7: Item "Use"/"Talk to Item" not working anymore 

### ISSUE THREAD

**Issue by rfht** [gemrb/gemrb#998] opened 2020-10-18 12:16 UTC
#### Bug description

In PST (built on OpenBSD), I can't use items anymore - neither from inventory screen, nor from the quick menu. I encountered this first with the note on Zombie number 1201 in the Morgue, then found the Copper Ring in the same place and any item (Charcoal Charm) can't be used anymore. A "Use" Button is shown in the lower left corner of the item description in the inventory, but nothing happens when I click it and the console log shows: `[GUIScript/WARNING]: Empty slot used?`

Compared it to 0.8.6 - there, the item description for the Zombie 1201 note and the Copper Earring show "Talk to Item" rather than "Use" in the lower left corner, and pressing it opens the dialog to manipulate it.

GemRB version:  0.8.7

#### Steps to reproduce
1. Obtain the note from Zombie 1201 in the Morgue. Go to inventory.
2. Right click on the note. Then click on "Use".
3. Nothing happens. Take a look at console log.
4. See error: `[GUIScript/WARNING]: Empty slot used?`

#### Expected behavior

Dialog to interact with the item opens as it did in 0.8.6.

**Comment by lynxlynxlynx** [comment] 2020-10-18 12:30
Thanks for the report. I think there was a misunderstanding when fixing one of the bugs and #986 will take care of it. If you want a quick fix, cherry-pick the DisplayItem change from e903950.

**Comment by chilvence** [comment] 2020-10-18 19:36
Is it worth me splitting this commit out to master? I think the rest of the bugs are subviews specific, but this one isn't

**Comment by lynxlynxlynx** [comment] 2020-10-18 20:42
We're getting close, so I don't think it's needed.

**Comment by Northfear** [comment] 2020-12-10 17:04
@chilvence is it still possible to split it into master? Changes from DisplayItem did help, but I'm still getting "Empty slot used?" when using  Jar of Embalming Fluid  for example.

**Comment by chilvence** [comment] 2020-12-10 17:39
Are you building from source? If so you can probably get away with just "git cherry-pick"-ing the relevant commit ( which is 
bd235ad ) . I don't manage the repository at all, I just send patches sometimes, so I can't split it out myself, but the commit should merge in without any problems.

**Comment by Northfear** [comment] 2020-12-10 19:22
Yeah, I did exactly that. Changes from "DisplayItem" fixed the note from 1201, but I'm still getting
`[GUIScript/WARNING]: Empty slot used?`
when using  Jar of Embalming Fluid from inventory, so I'm just confused whether it's working as expected or not quite.

**Comment by chilvence** [comment] 2020-12-10 20:24
It appears that in master, the use item button is trying to use the wrong inventory slot. I had forgotten about that until now. This is fixed in the subviews branch, unfortunately while there are some improvements to PST there, there are also currently some regressions that make it difficult to recommend playing it. I'll try and remember what exactly I changed in subviews to get it working and see if I can come of with a fix for you.

**Comment by bradallred** [comment] 2020-12-10 20:29
Alternatively, you could open issues for the remaining regressions so they can be fixed. I dont see any open ones regarding PST.

**Comment by chilvence** [comment] 2020-12-10 20:31
I'm talking about #1071 and #1020 , other than those two, it should be in good shape

**Comment by bradallred** [comment] 2020-12-10 20:33
#1020 is not a subviews regression. I've added the PST tag to the other. thanks.

**Comment by chilvence** [comment] 2020-12-10 20:41
Sorry, poor wording - not  a subviews regression, probably more of a case of it accidentally worked before, if not 100% correctly.

**Comment by bradallred** [comment] 2020-12-10 20:42
No, I mean there is literally no known difference in behavior between the branches for that issue anymore.

**Comment by lynxlynxlynx** [comment] 2020-12-10 20:42
I'd say to just wait, now we're really much closer to merging than when I last made this comment. :)

**Comment by Northfear** [comment] 2020-12-11 19:31
> It appears that in master, the use item button is trying to use the wrong inventory slot. I had forgotten about that until now. This is fixed in the subviews branch, unfortunately while there are some improvements to PST there, there are also currently some regressions that make it difficult to recommend playing it. I'll try and remember what exactly I changed in subviews to get it working and see if I can come of with a fix for you.

That would be nice. Hope it's not too much to ask. Waiting for subviews would be ideal, but I was hoping to make one more PS Vita build from master, since I have some SDL-related changes piled up and have no idea when I will be able to fix my stuff properly in subviews.

**Comment by chilvence** [comment] 2020-12-11 23:24
Can you try it with this? It looks up the slot index in the old itemhash table: 

https://github.com/chilvence/gemrb/commit/48900b4339f3bd657f10fde44a6b4f5bde287efd

There is one minor issue still, the inventory forces pause it seems, so unlike the original game you have to leave the inventory for the usage to take effect. But it should be better than not working at all.

**Closed** 2021-06-03 04:58 UTC
Labels: bug, subviews-recheck
