### ISSUE TITLE
[subviews] Closing windows with hotkey keep button highlighted

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#795] opened 2020-06-06 13:14 UTC
#### Bug description
Select a character, press 'I' to open inventory, on left bar, inventory is highlighted.
Press 'I' another time, window close but  inventory is always highlighted.
Close window with 'Esc' remove highlight on inventory.

Note : Closing window with 'Esc' don't remove highlight if the window is a disabled one.

Inventory is just an example

#### Expected behavior
closing window by hotkey or 'Esc' remove highlight on windows button

In master it's not good but the behaviour is different... I can open another bug for that if you want

**Comment by lynxlynxlynx** [comment] 2020-06-06 13:28
No, it's fine, this manual highlighting was always a bit off and we'll just fix it on subviews, since it'll be cleaner there.

**Comment by bradallred** [comment] 2020-06-09 17:13
the problem is that both opening and closing are accomplished via the hot key which "activates" the button which changes to the highlight state because it is "active". We basically need the window close handler to manually change the button state to "normal".

**Comment by bradallred** [comment] 2020-06-22 01:54
Interestingly some of the buttons in BG2 seem to be lacking a highlight. Am I wrong?

<img width="68" alt="image" src="https://user-images.githubusercontent.com/1126744/85241284-8c941e00-b3f8-11ea-98ef-7e172d943fbf.png">

I've hacked the button to always draw the "selected" frame and indeed they do seem to be missing. Surely these exist somewhere since they don't seem to be missing from the CHU for the secondary options window that we now ignore. Is there a way to manually fix it with `Button.SetSprites`?

**Comment by lynxlynxlynx** [comment] 2020-06-22 06:27
They're there in guiw, but missing in guiw8 and guiw10. Should be easy to fix indeed, since they all use the same bams, it's just that the bigger windows don't have the frame indices set for anything else but pressed and normal (default 0).

**Closed** 2020-06-23 06:38 UTC
Labels: subviews
