### ISSUE TITLE
 BG1: Create character alwas has last option "selected"

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#2153] opened 2024-09-25 05:44 UTC
#### Bug description
When starting a new game all the last option when creating a new character is "selected"

Is selected as the display is shown as selected but you can't continue until you select one.

#### Steps to reproduce
1. Go to Start new game
2. Click on character options
3. See error

#### Expected behavior
None is auto selected

#### Screenshots

![image](https://github.com/user-attachments/assets/98530360-0959-49d0-8202-f3c290962bd7)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [X] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment] 2024-09-25 06:01
Yeah, known problem with some PR open. Duplicate of #1740.

**Closed by lynxlynxlynx** 2024-09-25 06:01 UTC
Labels: bug
