### ISSUE TITLE
[subviews] Script error after first load screen in IWD/HoW

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#396] opened 2019-11-17 19:46 UTC
**Describe the bug**
Nothing too serious, I just discovered that when you load a savegame in IWD (HoW), when facing the party setup, there is a Python error but I can carry on.

```python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUICommonWindows.py", line 1854, in SelectionChanged
[Python/ERROR]:     UpdateActionsWindow ()
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUICommonWindows.py", line 670, in UpdateActionsWindow
[Python/ERROR]:     Button.SetBorder (1, color, 0, 1)
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'SetBorder'
```

**Comment by lynxlynxlynx** [comment] 2019-11-17 20:05
Looks like a dupe of #386, this is the action bar already.

**Comment by bradallred** [comment] 2019-11-21 20:27
I believe this is resolved.

**Comment by MarcelHB** [comment] 2019-11-21 20:47
I will check.

**Closed** 2019-11-21 21:15 UTC
Labels: iwd1, scripting, subviews
