### ISSUE TITLE
BG/BG2/PST: menu music keeps playing on first load 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1715] opened 2022-11-14 21:14 UTC
#### Bug description
For at least in PST, BG & BG2, you keep hearing the menu music playing even after entering the first savegame. A new load, or changing the map finally makes it stop.

IWD & IWD2 look good. Using OpenAL.

#### Steps to reproduce
1. Enter BG/BG2/PST and load a save game.

#### Expected behavior
No menu music after entering the game

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

**Comment by bradallred** [comment] 2022-11-14 21:16
looks to be a dupe of #1643

**Comment by MarcelHB** [comment] 2022-11-14 21:20
I'm sure this wasn't a problem until some time ago. Currently into something else, but maybe find what made it broke for what reason.

**Comment by MarcelHB** [comment] 2022-11-14 22:52
What about doing it like this?
```diff
@@ -2541,10 +2541,11 @@ void Map::PlayAreaSong(int SongType, bool restart, bool hard) const
        if (IsStar(*poi) && !MasterArea && SongType == SONG_BATTLE && core->HasFeature(GF_BREAKABLE_WEAPONS)) {
                poi = &core->GetMusicPlaylist(SongType);
                pl = SongType;
+       } else if (IsStar(*poi)) {
+               core->GetMusicMgr()->HardEnd();
+               return;
        }

-       if (IsStar(*poi)) return;
-
        //check if restart needed (either forced or the current song is different)
        if (!restart && core->GetMusicMgr()->IsCurrentPlayList(*poi)) return;
        int ret = core->GetMusicMgr()->SwitchPlayList(*poi, hard);
```

If `***` really encodes *no music*, then there is no music on this map and we stop what's playing, like the menu music (this is why it only affects some savegames: those without MUS file on the map), with exceptions from that rule to be encoded right before that.

**Comment by lynxlynxlynx** [comment] 2022-11-14 23:22
I think it's better to just call Soft/HardEndPL from python or before loading a map object for the first time. Menu music is not map music, so let's keep them separated. TextScreen.py already does it, but that's relevant only for new games, not loading.

**Closed** 2022-11-15 20:32 UTC
Labels: bug, system: audio
