### ISSUE TITLE
BG1: Lower half of the characters sometimes have weird colors in menus

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1356] opened 2021-07-14 09:22 UTC
#### Bug description
Sometimes the lower half of the paper dolls has weird colors, mostly red and magenta. I'm not sure how to trigger this, it occurred randomly and was resolved by closing and reopening the menu. 

I tested this in an unmodded BG1 install, but it also happened in my BGT install, so I guess it might apply to BG2 as well.

#### Steps to reproduce
1. Wish I knew

#### Screenshots
![unknown](https://user-images.githubusercontent.com/68446748/125597326-588e3e1a-2a65-4a99-afa5-87b1fcaf7ed5.png)

GemRB version (check as many as you know apply)
- [x]  master as of this issue (a335fc6255 AppImage from Build Bot)

**Comment by lynxlynxlynx** [comment] 2021-07-14 09:28
Looks like the lower half reverted to clown colors. So only one frame or cycle of the bam got properly colored, which is definitely a regression.

**Comment by bradallred** [comment] 2021-07-16 20:17
I believe this is fixed now

**Comment by lynxlynxlynx** [comment] 2021-07-16 21:05
yeah, user verified. :)

**Closed by lynxlynxlynx** 2021-07-16 21:05 UTC
Labels: bug, system: animations
