### ISSUE TITLE
[bug] iwd: mska death animation drawn twice

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#468] opened 2019-12-09 16:36 UTC
Old report:

>  double death animation in case of Mod[IE_ANIMATION_ID]: 0xF008 ResRef:mska (templeguardian4)

If you summon one and kill it, is the dying animation repeated? If yes, are any scripts involved or is really an animation problem?

**Comment by caillean7** [comment] 2020-01-16 15:45
The dying animation is started over halfway through. I tested on several installation, with and without IWD fixpack installed, with and without TotLM, but only my installation without HoW installed doesn't show that glitch.

Reproduce with

`CreateCreature(1,"LSKARMMS")`

Kill them with Ctrl.+Y or have them killed by the party. These armored skeletons have the following in their scripts:

```
IF
	!Global("KILL_LICH_MINIONS","MYAREA",0)
THEN
	RESPONSE #100
		Kill(Myself)
END
```

Doesn't cause this, but I tried commenting it out since it's the thing that has to do with their dying, just to be on the safe side. They don't have any active effects, and equipment-wise I couldn't find anything out of the ordinary. There are no state flags set.

**Comment by lynxlynxlynx** [comment] 2020-12-07 09:17
@fizzet this broke the first area of PST. The bottom zombie has a key to let you out of the starting room, but now never drops it. Somehow his stance never changes from IE_ANI_DIE and thus CheckOnDeath exits early. Please take a look.

**Comment by fizzet** [comment] 2020-12-08 15:28
Which one is that supposed to be? I can't seem to find any Zombies with keys...

**Comment by lynxlynxlynx** [comment] 2020-12-08 15:33
There are three in the first room, where you wake up. It was the southernmost one for me. Just ctrl-m them and you'll see.

**Comment by fizzet** [comment] 2020-12-08 16:57
It looks like there are several problems. The first is that, for PST animations, CharAnimations overrides `IE_ANI_DIE` with `IE_ANI_TWITCH` internally, and that never auto-switches, so the actor never changes stance away from `IE_ANI_DIE`. Even when fixing that, however, (or undoing the change that closed this issue), the zombie acts quite strangely and dies twice for a reason I haven't figured out yet.

I'm afraid I probably won't have much time to look into this more thoroughly soon.

**Comment by lynxlynxlynx** [comment] 2020-12-08 16:59
It's true that it's stance related and pst needs more work there, but we should at least if-def the check out for pst, since it immediately breaks it.

**Closed** 2020-12-12 22:23 UTC
Labels: bug, game: iwd1, system: animations

**Comment by lynxlynxlynx** [comment] 2021-05-02 18:10
Was looking for free bits and found we even have a documented one in pst for things like this:
`Actor.h:223:#define APP_DEAD         0x40000000  //used by the engine to prevent dying twice`

Something to keep in mind if further work will be required.
