### ISSUE TITLE
[subviews] IWD1 crash during battle with the Lich in Dorn's Deep: Tiers of the Dead

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1235] opened 2021-04-18 15:22 UTC
#### Bug description
I don't know if it specific to subviews branch but as it's the branch used... 

Approximate location : Position: ar6005 [1522.703] during battle with the Lich

I don't know how to reproduce, but here the information I have : 
```

[Python]: pause state None
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 1386, in <lambda>
[Python/ERROR]:     window.SetAction(lambda: TopWindowClosed(window), ACTION_WINDOW_CLOSED)
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 1360, in TopWindowClosed
[Python/ERROR]:     SelectionChanged()
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 1920, in SelectionChanged
[Python/ERROR]:     UpdateActionsWindow ()
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 662, in UpdateActionsWindow
[Python/ERROR]:     CurrentWindow.SetupControls (globals(), pc, ActionBarControlOffset)
[Python/ERROR]:   File "../gemrb/GUIScripts/MetaClasses.py", line 44, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: RuntimeError: Can't find GameControl!
Method Docs:
===== Window_SetupControls =====

**Prototype:** GemRB.SetupControls (WindowIndex, dict, slot[, Start])

**Metaclass Prototype:** SetupControls (Slot[, Start])

**Description:** Sets up all 12 action buttons for a player character, 
based on preset preferences and the character's class.

**Parameters:**
  * WindowIndex - the buttons' window index
  * Slot        - the player character's index in the party
  * Start       - action offset

**Return value:** N/A

**See also:** [[guiscript:Button_SetActionIcon]], [[guiscript:SetDefaultActions]], [[guiscript:Window_SetupEquipmentIcons]]
[GUIScript]: Loading Script GUILOAD.
[ResourceManager]: Found 'guiload.chu' in 'chitin.key'.
[ResourceManager]: Searching for 'guisrsvb'...
[ResourceManager]: Found 'guisrsvb.mos' in 'chitin.key'.

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x0000555555dd1ea0 in ?? ()
(gdb) bt
#0  0x0000555555dd1ea0 in ?? ()
#1  0x00007ffff7d1202f in GemRB::Control::SetValue (this=0x55555af0cc70, 
    val=1222)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/GUI/Control.cpp:164
#2  0x00007ffff7d373de in GemRB::ScrollView::UpdateScrollbars (
    this=0x555556352538)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/GUI/ScrollView.cpp:189
#3  0x00007ffff7d37bb4 in GemRB::ScrollView::ScrollTo (this=0x555556352538, 
    newP=..., duration=0)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/GUI/ScrollView.cpp:333
#4  0x00007ffff7d37a06 in GemRB::ScrollView::ScrollDelta (this=0x555556352538, 
    p=..., duration=0)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/GUI/ScrollView.cpp:313
#5  0x00007ffff7d379ac in GemRB::ScrollView::ScrollDelta (this=0x555556352538, 
    p=...)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/GUI/ScrollView.cpp:308
#6  0x00007ffff7d3b3a0 in GemRB::TextArea::TrimHistory (this=0x5555563523a0, 
    lines=1)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/GUI/TextArea.cpp:428
--Type <RET> for more, q to quit, c to continue without paging--
#7  0x00007ffff7d3b448 in operator() (__closure=0x55556434baa8)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/GUI/TextArea.cpp:452
#8  0x00007ffff7d3cacc in std::__invoke_impl<void, GemRB::TextArea::AppendText(const String&)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/invoke.h:60
#9  0x00007ffff7d3c9bc in std::__invoke_r<void, GemRB::TextArea::AppendText(const String&)::<lambda()>&>(struct {...} &) (__fn=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/invoke.h:153
#10 0x00007ffff7d3c8a2 in std::_Function_handler<void(), GemRB::TextArea::AppendText(const String&)::<lambda()> >::_M_invoke(const std::_Any_data &) (
    __functor=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/std_function.h:291
#11 0x00007ffff7d7cc52 in std::function<void ()>::operator()() const (
    this=0x55556434baa8)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/std_function.h:622
#12 0x00007ffff7de844e in GemRB::Timer::Update (this=0x55556434ba90, 
    time=7117305)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/Timer.h:66
#13 0x00007ffff7dd7741 in GemRB::Interface::Main (this=0x55555556eb50)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/core/Interface.cpp:935
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x0000555555555385 in main (argc=3, argv=0x7fffffffdba8)
    at /home/dupontr/Downloads/gemrb_sub/gemrb/gemrb/GemRB.cpp:73
(gdb) quit
```

edit : I have done this battle 3 or 4 times and this is the only crash.

**Comment by lynxlynxlynx** [comment] 2021-04-18 17:55
Looks like you had some bad state from before, so this is not that useful. Something eventually caused the load to not complete fully, not restarting the gc and/or left old callbacks being present (it crashed on PerformAction). I'll close this, but please reopen if you manage to reproduce again, consistently.

**Closed by lynxlynxlynx** 2021-04-18 17:55 UTC
Labels: subviews
